### ISSUE TITLE
DT & HT BPM, mod HP [Feature Request]

### ISSUE THREAD

**Issue by xenosu** [Piotrekol/StreamCompanion#10]
Exactly what the title says. Have a variable that calculates mod BPM, and another for mod HP.

**Comment by Piotrekol** [comment]
modded bpm will be in next release, as for HP, I've no idea how math for it works.

**Comment by xenosu** [comment]
modded bpm is bpm*1.5 for DT and bpm*0.75 for HT
hp is the same as od and ar but it's not affected by DT or HT iirc
so hp is hp*0.5 with EZ and hp*1.4 with HR but is the same with other mods
