### ISSUE TITLE
add time token

### ISSUE THREAD

**Issue by InvisibleSymbol** [Piotrekol/StreamCompanion#100]
Close if you don't want to add it, just would be nice to have the time in the top right while retry spamming a map c:

**Comment by KarBoy2314PL** [comment]
isn't there already a time token but in miliseconds?

**Comment by InvisibleSymbol** [comment]
Bit confusing but what you mean is the map time. I'm talking about the real time (for example 13:35:45)

**Comment by Piotrekol** [comment]
`!LocalTime!` token will be available in next release
