### ISSUE TITLE
SC stuck at loading 100 maps, can't load the rest of them.

### ISSUE THREAD

**Issue by Ezephra** [Piotrekol/StreamCompanion#104]
Hi,

I used SC for the very first time and I did some configuration for my stream setup. 
Then, when I start playing a map, it says: data not found - "song name" which I begun to change all kind of settings, like disabling Live Visualizer and some other options in order to get the name/ title of the map on the screen for the stream.

After all of this, I realized on the SC is still "loading" the whole time. 
On a logical thought, I think that is my issue. 
It's stuck at 100 maps, even after restarting the SC, it's still fixed on 100 maps (from +1700 maps on this computer).

![image](https://user-images.githubusercontent.com/25911174/67778896-2e2ebf80-fa64-11e9-964b-85c8bce22156.png)

Thanks for the help,

Ezephra

**Comment by Ezephra** [comment]
Even deleting and re-instralling the SC is still stuck

**Comment by Piotrekol** [comment]
are you playing on official osu! servers? (in other words: are you running modified osu! client?)

**Comment by Ezephra** [comment]
Yes, I'm playing on Osu! official servers ("bancho" if I'm not mistaken)

**Comment by Piotrekol** [comment]
"faulty" beatmap: https://osu.ppy.sh/beatmapsets/1030664#osu/2155559 😒
