### ISSUE TITLE
osu!.db problem

### ISSUE THREAD

**Issue by FeellsBadSkillz** [Piotrekol/StreamCompanion#107]
Hi,
I've been using SC since March 2019 and until this day I haven't any problems.
Now with the latest updates i've been getting the osu!.db problem (I'm using the latest update https://prnt.sc/ptfp2t )
I've try to dis install and reinstall SC but with no results.
I also try to remove all song that can overflow the score but nothing.
I need help.
Screenshot allegated with the error
https://prnt.sc/ptfn93

**Comment by Piotrekol** [comment]
I was waiting for someone with this issue :).
That issue was also happening before - it's just that SC wasn't ever reporting osu!.db load issues, until few updates ago.

To be able to fix that, I'll need your osu!.db file - hop on discord and shoot me a DM with that file https://discord.gg/N854wYZ

**Comment by Piotrekol** [comment]
osu!.db format has changed. will fix tomorrow - meanwhile, I suggest switching to osu! stable (note that doing that __WILL RESET YOUR OSU DATABASE__)

**Comment by FeellsBadSkillz** [comment]
Fow now cutting edge users, switch on to stable

**Comment by ElectricityMachine** [comment]
Issue should be re-opened. I'm on stable and have the same issue.

**Comment by Fleepy** [comment]
> Issue should be re-opened. I'm on stable and have the same issue.

Yeah, Im still getting it too and im on stable.
