### ISSUE TITLE
Allow POST'ing of map data to any url [feature request]

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [Piotrekol/StreamCompanion#12]
I run a small bot and it would be great if you could allow the current map playing data to be POST'd to any url instead of only to osu!post servers.

**Comment by omkelderman** [comment]
put the osu post server url in your hosts file :wink:

but in all seriousness, yes pls :smile:

**Comment by Piotrekol** [comment]
I'll make endpoint url editable in the next release.

> current map playing data

Only things that are currently sent are mapName(artist, title, difficulty), mapId/setId and your current status(playing,listening..)

**Comment by BatedUrGonnaDie** [comment]
Since the mapId/setId is sent then it should be fine because I could just query the osu api for the complete information if I needed something more than what was sent, yes?

**Comment by Piotrekol** [comment]
Sometimes these ids can be unavailable because of user playing map that is unsubmitted or loaded old map(with old .osu file with didn't contain mapIds, so SC has no idea about these)

**Comment by BatedUrGonnaDie** [comment]
Ah gotcha.  Thanks for the info it's greatly appreciated.

**Comment by Piotrekol** [comment]
Added.
