### ISSUE TITLE
Initial Setup issue

### ISSUE THREAD

**Issue by Thurion666** [Piotrekol/StreamCompanion#120]
When i start the program it says that i need to enable "MSN" option and change a map once.
When i do it as it says, it doesn't do anything, it keeps happening even when i waited a few months for a new release of the program, it just doesn't work for me. I tried reinstalling it and osu, keeps happening the same. What i can do?, do i need to delete some user files or something?

**Comment by Piotrekol** [comment]
According to messages on discord, you managed to resolve this shortly after creating this issue :).
