### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by Kici33** [Piotrekol/StreamCompanion#121]
Updater contains a lot of bugs. It can't override files. I think program should auto-close when updating because there are errors when trying to update. After update I've got crash about SQL (or something writed in this way if I remember correctly). Next thing is that program is overriding files in specific way, that windows is blocking that.

**Comment by Piotrekol** [comment]
First off, horrible "error" report
1. Updater already does what you mentioned.
2. SQL error - more details needed.
3. it does not write to any files outside of SC Files folder (only exception to that is ingameOverlay with copies one file to osu! folder)

this sounds more like your antivirus being a jerk.
