### ISSUE TITLE
InGame overlay doesn't work

### ISSUE THREAD

**Issue by qqawsedr8** [Piotrekol/StreamCompanion#126]
Im trying to run ingame overlay but nothing appears. I've tried to reinstall SC with no luck either.

**Comment by Piotrekol** [comment]
Have you enabled ingame overlay in settings in General tab?

**Comment by qqawsedr8** [comment]
> Have you enabled ingame overlay in settings in General tab?

Yes i even tried older versions of SC and same thing.

**Comment by Piotrekol** [comment]
if you have your osu open while starting SC, does this show up? 
![image](https://user-images.githubusercontent.com/4990365/72183591-ad3e5d80-33ee-11ea-98e4-cad56690729d.png)

**Comment by qqawsedr8** [comment]
Only if i have osu! open before i open SC

**Comment by Piotrekol** [comment]
Do you have any pattern set to be displayed on screen? try creating one with just plain text(no tokens) and save event set to `All` at default x,y(200,200)
![image](https://user-images.githubusercontent.com/4990365/72185187-8550f900-33f2-11ea-9d86-62c3d8dc1a9d.png)

**Comment by qqawsedr8** [comment]
I've tried that too

**Comment by Piotrekol** [comment]
Install [this version of ingame overlay](https://ci.appveyor.com/api/buildjobs/1j12qc8u1kf3pyxn/artifacts/innoSetup%2FOutput%2FStreamCompanion%20-%20ingameOverlay%20Setup.exe) and see if anything changes. If it doesn't you'll have to attempt to manually enable overlay by executing some command in console to see if that fails.. hop on discord if there is need for that.

**Comment by qqawsedr8** [comment]
Ok i will give it a shot when i can. Thanks for your help

**Comment by qqawsedr8** [comment]
> 
> 
> Install [this version of ingame overlay](https://ci.appveyor.com/api/buildjobs/1j12qc8u1kf3pyxn/artifacts/innoSetup%2FOutput%2FStreamCompanion%20-%20ingameOverlay%20Setup.exe) and see if anything changes. If it doesn't you'll have to attempt to manually enable overlay by executing some command in console to see if that fails.. hop on discord if there is need for that.


It looks like this error appeared but i didn't see it because it didn't appear on top of osu!
![Screenshot_3](https://user-images.githubusercontent.com/57594514/72203099-05697400-3470-11ea-857f-61f9f6f8aac9.png)

**Comment by GoodGamist** [comment]
I had the same issue and I also tried what was mentioned above... 

I even tried to use the ingame overlay setup version from here and it just said to run SC in administrator mode, which I did but it didn't fix the problem

**Comment by qqawsedr8** [comment]
> I had the same issue and I also tried what was mentioned above...
> 
> I even tried to use the ingame overlay setup version from here and it just said to run SC in administrator mode, which I did but it didn't fix the problem

Solved: Disable compatibility mode
