### ISSUE TITLE
The program shows incorrect values for HP and OD during playing DT.

### ISSUE THREAD

**Issue by SentimentalDesu** [Piotrekol/StreamCompanion#127]
HP values do not change if you add DT mode.
Even if you're playing Yomi Yori with DT, the program will never show OD values higher than "10".
The program always shows correct values for AR though.
(I talk about !mOD!, !mHP! and !mAR!)

**Comment by Piotrekol** [comment]
correct me if I'm wrong - HP is only affected by HR/HT mods.

OD internally is calculated correctly, but output is capped to 0-10 range:
https://github.com/Piotrekol/StreamCompanion/blob/master/plugins/ModsHandler/DifficultyCalculator.cs#L102

**Comment by SentimentalDesu** [comment]
HP is affected by DT too (https://osu.ppy.sh/help/wiki/Game_Modifiers).
Can i edit the program code a bit and set 0-11.1 range?
I make overlays and want the program to show exact value for OD.

**Comment by Piotrekol** [comment]
https://osu.ppy.sh/help/wiki/Beatmap_Editor/Song_Setup/#overall-difficulty
```
Easy: Halves the OD value.
Hard Rock: Multiplies the OD value by 1.4, up to a maximum of OD10.
Double Time: The OD value is not affected, but due to the 50% play speed increase this causes hit windows to be 33% shorter.
Half Time: The OD value is not affected, but due to the 25% play speed decrease, this causes hit windows to be 33% longer.
[...]
the OD values provided are only for comparison: the actual OD value is always a number from 0 to 10.
```
mOD will have to stay as-is, but I have nothing against creating separate token for non-capped OD value.

**Comment by SentimentalDesu** [comment]
Okey, thanks for the answers.
And for your work.

**Comment by Piotrekol** [comment]
![image](https://user-images.githubusercontent.com/4990365/72188601-fac0c780-33fa-11ea-85db-733ea7513505.png)

**Comment by SentimentalDesu** [comment]
Oh my god.
Thank you very much!
I'm so glad you did it. :D

**Comment by SentimentalDesu** [comment]
Probably it's a bit of a silly question,
but can i download a release that includes the changes?

**Comment by Piotrekol** [comment]
![WI7Dvv7S82](https://user-images.githubusercontent.com/4990365/72191558-d668e900-3402-11ea-9921-cf979bf04730.png)
![hBATUVL6fy](https://user-images.githubusercontent.com/4990365/72191576-e8e32280-3402-11ea-8395-cb15bb512755.png)

**Comment by SentimentalDesu** [comment]
Thank you very much again. :D

**Comment by SentimentalDesu** [comment]
And you actually were right, when you said that HP is not affected by DT.

**Comment by SentimentalDesu** [comment]
There is a problem with mOD-Real.
If you play a high star map with only HR, it shows OD 11.1.
Can you set limit in 10 for non-DT/NC plays?
