### ISSUE TITLE
Not detecting at the setup that I'm playing

### ISSUE THREAD

**Issue by Citrom67** [Piotrekol/StreamCompanion#128]
At the setup process when you should play **a certain map** with **specific mods...**
I do what it says but still don't progresses further and just says _"waiting..."_ and it doesn't do anything else
I have the **latest stable version of osu!(currently is b20200118.2)** and I use a **windows 10 pro**
I've never really bumped into this issue even tho I installed it several times but it was always working fine before. 
But now I tried to install it quite a few times now and still didn't do anything than _"waiting..."_

**Comment by thinkingaustin** [comment]
yeah i have the same problem too

**Comment by Piotrekol** [comment]
Try updating to this version of SC:
https://ci.appveyor.com/api/buildjobs/i8q8ww0auu25eq84/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe
If it happens to work correctly, just continue to use it - it'll receive update notifications as usual.
