### ISSUE TITLE
SC doesn't recognize enabling MSN Option

### ISSUE THREAD

**Issue by dominikheinz** [Piotrekol/StreamCompanion#13]
When I start SC and check the MSN Live Status option in osu it is not recognized in StreamCompanion and the setup doesn't proceed. 
Win 10 x64, Osu stable build

**Comment by Piotrekol** [comment]
- [ ] Make sure that MSN is enabled ingame.
- [ ] Run SC and osu! on same permission level (both as normal user, or both as administrator)
- [ ] Make sure that your antivirus isn't doing something weird(especially sandboxing) - try adding exception in it.

**Comment by Piotrekol** [comment]
assuming fixed
