### ISSUE TITLE
Feature request: Duplicate current song's background to SC's directory

### ISSUE THREAD

**Issue by KarBoy2314PL** [Piotrekol/StreamCompanion#131]
in a response to this https://redd.it/ec0id3

basically SC would fetch current song's background, put it in it's own folder under a specific name just so OBS can retrieve it to do stuff with it

**Comment by Piotrekol** [comment]
Will save in files directory as `BG.png`(regardless of if an image is actually png) and is also provided in token form `!backgroundImage!` as base64 encoded image, which can be also used in TCP/WebSocket outputs.
