### ISSUE TITLE
Feature Request: Math for tokens/formatting

### ISSUE THREAD

**Issue by sometimeszzzzzzz** [Piotrekol/StreamCompanion#140]
It would be nice to be able to use some math functions in Output patterns formatting section.
E.g. something like !totaltime//60000:00! : !totaltimes%//60000:00!
outputs 04 : 35
Math functions like // for floor division and % for modulus would be nice, also :00 for formatting numbers.

More examples:
Objects: !circles + sliders + spinners!
Objects: 450

Map completion: !time/(totaltime/1000):0.00!%
Map completion: 26.3%

Or maybe like {!totaltime! + !300! + 100 : 0.00} where {} signifies math being used, and :0.00 for formatting. That might actually be neater lol
Whichever way you decide to implement it with, I'm fine with it as long as I can use math in the formatting section :)

**Comment by Piotrekol** [comment]
Any functions in particular that you would expect to be there by default - like log, sin, floor etc.? (can be added in a later release anyway)

**Comment by sometimeszzzzzzz** [comment]
Tysm c:
I don't see any use cases for any functions other than really basic math stuff for now, but if I ever find a use case for some function, I'll probably try to add it myself.
