### ISSUE TITLE
Feature Request: mUR for mods DT and HT

### ISSUE THREAD

**Issue by sometimeszzzzzzz** [Piotrekol/StreamCompanion#141]
mUR is UR/1.5 for DT
and ~~UR*1.5~~ UR/0.75 for HT
I think that's what a lot of players would want to see when playing dt or ht

**Comment by uzervlad** [comment]
Shouldn't it be UR/0.75 for halftime?

**Comment by sometimeszzzzzzz** [comment]
oops, my bad, it is UR/0.75
