### ISSUE TITLE
background import reloads and/or doesn't work on status change

### ISSUE THREAD

**Issue by KarBoy2314PL** [Piotrekol/StreamCompanion#148]
hey there, i know i might seem whiny about a thing that i suggested, but im not sure if there's going to be anyone else reporting this

when changing status, bg disappears and appears again
however, if you are Playing, bg disappears and comes back when you'll be Listening

IMO it shouldn't do that, it should reload when a mapset or a diff changes, not when status changes

**Comment by KarBoy2314PL** [comment]
wait, what? after further investigation, if a diff has state of Not updated, bg during Listening is gone, but when you are Playing that diff bg appears again?! some very inconsistent results, definitely not expected

**Comment by Piotrekol** [comment]
`also SC may or may have not crashed multiple times on me and it sent info to you`
Can you attempt to find when it crashes - then update to [this version](https://ci.appveyor.com/api/buildjobs/c7h30ukg4i82tdc1/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe) and do the same steps - it should provide me with enough information to know how to proceed further.
https://sentry.io/share/issue/43fd2357d1ea40e0997d6c56a2d4da7b/

**Comment by Piotrekol** [comment]
Removed download link from release page until this is resolved to avoid SC automatically updating to this version.
![image](https://user-images.githubusercontent.com/4990365/76788046-7acc2a80-67ba-11ea-9dcb-a0cd687ae593.png)

**Comment by KarBoy2314PL** [comment]
> `also SC may or may have not crashed multiple times on me and it sent info to you`
> Can you attempt to find when it crashes - then update to [this version](https://ci.appveyor.com/api/buildjobs/c7h30ukg4i82tdc1/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe) and do the same steps - it should provide me with enough information to know how to proceed further.
> https://sentry.io/share/issue/43fd2357d1ea40e0997d6c56a2d4da7b/

didn't manage to find the problem, my suspicions are either:
- my very poorly performing hard drive, so much so that it's not keeping up with reading ram and moving backgrounds at once alongside Chrome, Discord, OBS, SC, GIMP and Twitch Launcher <-- on top of that, starting the game and going straight into song select and spamming F2 manages to give me lags of upwards 3000ms
- invalid characters in the skin name (like japanese alphabet?) <-- after some testing, that's false
- invalid characters in a background name <-- also false, [this set](https://osu.ppy.sh/beatmapsets/112651#osu/292577) has a bg in foreign language (diff is masterpiece ar10), rename it to the proper name (it's in the .osu file), load it and nothing bad happens

also during testing, i managed to break the search system, which sent some info to peppy as well

**Comment by Piotrekol** [comment]
original issue was fixed in 08a0e49b556bf13d6d9f509880eff4118ddcc3e8
Skin path token issue still remains until I receive more error reports in sentry (try-catched so SC won't crash)

**Comment by Piotrekol** [comment]
(skin path token issue) seems that reader likes to read malformed skin names:
![image](https://user-images.githubusercontent.com/4990365/84167078-0e3d9080-aa76-11ea-9fe3-ea73a242a2b8.png)
"handled" in 24680bcbf8905e326c9b1c4c1dca17734a8eea09
