### ISSUE TITLE
pp estimation is incorrect

### ISSUE THREAD

**Issue by ceilingwaffle** [Piotrekol/StreamCompanion#15]
This play for Waldschrein HDHR was worth 470.89 pp but in the video the estimator ends on 462.09 pp: https://youtu.be/qa2VoYjPBD0?t=5m15s (470.89 shown on the leaderboard: https://i.imgur.com/uTICCh3.png )

Also it's wildly broken, showing over 4000pp at some points, shown here: https://clips.twitch.tv/HungryCutePlumageTTours

Using version 180221.18.
Screenshot of "map formatting" settings: https://i.imgur.com/hSX53F4.png

**Comment by Piotrekol** [comment]
First one fixed https://github.com/Piotrekol/OppaiSharp/commit/931fdf8dc63b23421a1b57b73f64ee7d72dd7ec2

Second I've honestly no idea what the happened there, but I'll include something extra for when next time this happens it'll be reported to me with debug info

**Comment by Piotrekol** [comment]
Everything should be fixed in next release :)

**Comment by ceilingwaffle** [comment]
Nice. Thanks for all the work you've put into this :D
