### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Snowz01** [Piotrekol/StreamCompanion#150]
Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

**Comment by Piotrekol** [comment]
Please provide more details.

**Comment by Snowz01** [comment]
When opening the setup .exe I get a prompt box saying "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."

**Comment by Snowz01** [comment]
> Please provide more details.

When opening the setup .exe I get a prompt box saying "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."
