### ISSUE TITLE
Click Counter does not save on exit

### ISSUE THREAD

**Issue by ohabu** [Piotrekol/StreamCompanion#151]
Click counter token works fine BUT,
"keyCounts = 967831|,~547436" stuck in settings.ini. 
Every time i launch SC, it starts with those numbers and adds up. If i open settings dialog before exit  SC, it saves the updated counter numbers.

**Comment by cemoral** [comment]
That was not solved the above problem

**Comment by Piotrekol** [comment]
create another issue if you believe you have problems with this.
retested and everything works as expected.
