### ISSUE TITLE
Showing wrong beatmap

### ISSUE THREAD

**Issue by AngelSagiri** [Piotrekol/StreamCompanion#152]
Hi!
So when I listen to a song and I don't play it everything works well, but when I start playing it, the Stream Companion shows a different map. *That doesn't happen with all maps*
Greetings and I count on your help.
P.S. Sorry for my English.

**Comment by Piotrekol** [comment]
I had it happen once or twice before myself but haven't taken a look at it. I'll check it whenever I encounter this bug again.

**Comment by AngelSagiri** [comment]
I believe its because I have almost 100k maps, btw thanks for fast answer.
