### ISSUE TITLE
support mania mode

### ISSUE THREAD

**Issue by sinsa92** [Piotrekol/StreamCompanion#154]
Was StreamCompanion intentionally created only for osu!standard? Well it would be nice to use it also in other modes. Since I play osu!mania mainly, i noticed a few things:
 - On the live visualizer, 320 and 200 hits are not registered.
 - PP cannot be calculated

Would it be possible to support all modes?

Thanks in advance!

**Comment by Piotrekol** [comment]
SC supports all game modes except for ctb.
mania pp is score bound, meaning that it scales with current achieved score starting at 500k
320/200 hits are geki and katsu in osu! (#84). Are you asking for them to be shown in visualizer when playing mania?

**Comment by Sinsambin** [comment]
I'd like to see the hits aswell as the live pp count in the visualizer if it's possible.

**Comment by uzervlad** [comment]
> mania pp is score bound, meaning that it scales with current achieved score starting at 500k
I'm pretty sure there is a way to scale current score to 1kk so SC would always show current pp

**Comment by Piotrekol** [comment]
Closing as mania is supported & I'm not planning on modifying mania pp calc (scaling).
Feel free to submit PR for scaling changes.
