### ISSUE TITLE
StreamCompanion ingame not downloading beacause its virus

### ISSUE THREAD

**Issue by HDAndreasEST** [Piotrekol/StreamCompanion#157]

**Comment by l3lackShark** [comment]
In-game overlay works by performing an OpenGL injection. It is common for such programs to be flagged by AVses. Please disable yours if you want to use it.

**Comment by Piotrekol** [comment]
It should be mostly resolved for the next release.
[Scan result of overlay setup after changes made in commit above](https://www.virustotal.com/gui/file/0509449a8e75ee272985861600149a002730ecec8cf6041507c35216051987eb/detection)
[...compared to current release overlay setup](https://www.virustotal.com/gui/file/1411dedf8c1d0554ee6ddcacdcd4d9cbdb29090162b3342928cb4ac5ac5bea8f/detection)

**Comment by HDAndreasEST** [comment]
Thank you
