### ISSUE TITLE
Can't complete install because Windows, VirusTotal says it's a virus. Is it a false positive/is there an explanation for this?

### ISSUE THREAD

**Issue by UltimateKaren** [Piotrekol/StreamCompanion#162]
![osuppcountersetuppossiblemalware](https://user-images.githubusercontent.com/65194640/84618735-e55b3800-ae87-11ea-8179-6074ed93a637.png)

I then scanned it with Windows Defender and Malwarebytes and found nothing. Is this something to be worried about or should I get it anyway?

**Comment by Piotrekol** [comment]
false positive
