### ISSUE TITLE
Map data not found on imported maps while SC is running

### ISSUE THREAD

**Issue by Hallowaa** [Piotrekol/StreamCompanion#168]
When importing a map while SC is running, it won't be loaded on SC until it gets closed and opened again.  It says "map data not found:" and then the name of the map. I've tried letting SC through the firewall as well as running both SC and osu! as administrator but this did nothing. Also, when importing a new map that has the same name as a map you had before, it shows the name and difficulty of the map you already had, and not the new one, but ofc this might be related to the first problem.

**Comment by Hallowaa** [comment]
Alright, I've asked other people who use SC about this, and it seems like I'm the only one who has this problem, so it's probably not a problem with the program. I'll keep this issue up tho, just in case anyone knows about a solution, but you can close it if you want.

**Comment by Piotrekol** [comment]
> When importing a map while SC is running, it won't be loaded on SC until it gets closed and opened again

Make sure that osu! location detected by SC is correct (especially if you have multiple osu! instances). You can check that in settings in `General` tab

**Comment by Hallowaa** [comment]
I just checked. The "osu! Directory" is pointing at the right folder in AppData->Local , and the songs folder location is inside the osu! folder. I just tried adding a song and check if it pops up in the songs folder, and it does, but it's not being read by SC.

**Comment by Piotrekol** [comment]
in your SC install folder open settings.ini and check the value of `SongsFolderLocation`. in your case it should be just `Songs`.

You can also try starting SC while holding ctrl+shift(or enabling console logger + debug logging level in general tab - does the same thing) and see if anything appears whenever you load new song in osu!

**Comment by Hallowaa** [comment]
the SongsFolderLocation is correct, it is just Songs. Tho I think this is not a directory problem, otherwise SC wouldn't get any songs at all. I have opened the debugger and this is what I get: 
![image](https://user-images.githubusercontent.com/47676605/87032594-26274200-c1e5-11ea-85a7-f1f73b26747d.png)
SC seems to find data about it, but still says
![image](https://user-images.githubusercontent.com/47676605/87032667-3f2ff300-c1e5-11ea-930b-50735c36cfbc.png)
(This is on a song I just imported during runtime, since the problem is with songs that are imported while SC is running. The problem goes away if I restart SC)

**Comment by Piotrekol** [comment]
> SC seems to find data about it

it doesn't, that's just event info that later is used to find actual map data(with it fails to find)

Restart SC with that log window still enabled. is `OsuSongsFolderWatcher` plugin loaded at startup?

**Comment by Hallowaa** [comment]
yes, it is being loaded
![image](https://user-images.githubusercontent.com/47676605/87033367-6509c780-c1e6-11ea-8d77-90d4893c7b4a.png)

**Comment by Hallowaa** [comment]
> Alright, I've asked other people who use SC about this, and it seems like I'm the only one who has this problem.

Nevermind, I've been going around twitch to see if this happened to other streamers and it does happen to some, but not to others. Really weird.

**Comment by Piotrekol** [comment]
Should be fixed in the latest release.
