### ISSUE TITLE
osuOverlayPlugin

### ISSUE THREAD

**Issue by Nerxxy** [Piotrekol/StreamCompanion#169]
upon loading i get a message saying - Plugin "osuOverlayPlugin" could not be loaded..... 
Errors:
system.typeloadexception: could not load type
'streamcompaniontypes.interfaces.imodule' from assembly
'streamcompaniontypes, version=3.1.0.0, cultural=neutral,
publickeytoken=null'.

**Comment by Piotrekol** [comment]
update ingameoverlay.
