### ISSUE TITLE
StreamCompanion crashes upon launch consistently.

### ISSUE THREAD

**Issue by traydenpoke** [Piotrekol/StreamCompanion#172]
StreamCompanion crashes upon launch. It stays open without being touched, but as soon as I play a map or even switch beatmaps, the app crashes and gives me the same error log consistently. (see below). I went back to an old version, but with a recent osu! update (that the most recent ver. of SC appears to have fixed) the old version no longer works. (I ran SC and osu! with and without administrator, changed nothing)

[Image of Logs](https://prnt.sc/tke47j)

**Comment by Piotrekol** [comment]
have you tried reinstalling SC? this looks like a permissions issue. you can backup your settings.ini if necessary.

**Comment by traydenpoke** [comment]
I resinstalled SC several times, including installing SC on the C: drive, and then /osu! folder (located on D: drive for storage sake); same exact error.

**Comment by Piotrekol** [comment]
remove `BackgroundImageProvider.dll` from your `SC/plugins` folder and see if the problem still persists.

**Comment by traydenpoke** [comment]
removing the file you mentioned fixed the problem, thank you.

**Comment by Piotrekol** [comment]
that isn't a valid fix but I'll try to investigate anyway 
![image](https://user-images.githubusercontent.com/4990365/87862887-2649df00-c955-11ea-8525-fb87f448c710.png)
