### ISSUE TITLE
Does not work with Wine, dont getting the MSN Live data

### ISSUE THREAD

**Issue by YourSandwich** [Piotrekol/StreamCompanion#173]
Hello dear dev,
im curently playing osu on linux and got everything to work, but one minor issue is that if i would like to stream i cant use your Application. I can install it in the same wineprefix as Osu and its gona start without any problems but after asking to playing a map with hdhrdtnf mods its just simply not working. I assume that there is some dll missing in wine. Could you provide me the info what dll is the Program useing to grab playing songs data?

Regards
YourSandwich

**Comment by Piotrekol** [comment]
There are several users that have SC running under Linux without major issues. Maybe this was related to recent issues with memory detection. Could you try to retest using latest release?
