### ISSUE TITLE
map title/artist/etc not listed in tokens anymore

### ISSUE THREAD

**Issue by pavlukivan** [Piotrekol/StreamCompanion#175]
it worked yesterday... i think? at least it worked 2 days ago

Map title isn't shown via output patterns, and it's gone from tokens preview: https://i.imgur.com/kszGJdJ.png

**Comment by Piotrekol** [comment]
Please retest on the latest release. This could happen if you were one of the affected users with broken osu memory reading(doesn't happen for everyone) and have MSN disabled ingame so it had nothing to fall back to.

**Comment by pavlukivan** [comment]
it works now, but i had MSN enabled

**Comment by pavlukivan** [comment]
well, since the issue doesn't occur to me atm i'll close it
