### ISSUE TITLE
Wrong Difficulty calculation

### ISSUE THREAD

**Issue by leonbtww** [Piotrekol/StreamCompanion#178]
Sometimes the pp preview calculates and shows the pp for the wrong difficulty. Like there is a 3 Star and 5 Star version. And I choose the 3 Star version the calc shows 200pp at the mid of the map.

But as soon as I play the map everything is fine. Its just the preview.

**Comment by Piotrekol** [comment]
can you try disabling MSN support ingame and see if SC works at all? If it doesn't then it's an issue with osu memory reader, with should be fixed in the coming SC release.

**Comment by leonbtww** [comment]
Nope. Must be the memory reader. I am patiant and wait 'till the next update. Thanks for the fast reply

**Comment by Piotrekol** [comment]
with you can download now from the releases page.

**Comment by leonbtww** [comment]
that was fast. Thanks

**Comment by leonbtww** [comment]
I've tested it and now it works perfectly. Thank you.
