### ISSUE TITLE
Can't find source for the "Memory"

### ISSUE THREAD

**Issue by llllllllll** [Piotrekol/StreamCompanion#18]
I am trying to follow the control flow around reading the mod values when playing using a mix of the source and logs. I cannot find the `MemoryDataFinder` class which is what I believe is being used to actually get this information. The logs show:

```
>Got <beatmap-id> & <mods> from memory
>Found data using "Memory" ID: <beatmap-id>
```

But I don't see a `DataFinder` with a `SearcherName` of "Memory". Also, the only log line I see with `>Got` is `MapStringFormatter.cs:64`, but that doesn't match this line.

I do see an `osuMemoryID` directory in the `MapDataFinders` but it appears to only contain the objects needed to set up the settings in the GUI. Is there a chance that the finder class wasn't committed by accident?

I could be going down the complete wrong path, but this is what I have found so far. Also, thank you for publishing this awesome project!

**Comment by Piotrekol** [comment]
Some parts of SC source code aren't in this repository, that includes sentry error reporting and everything related to reading osu! memory, with "memory" searcher does.

**Comment by llllllllll** [comment]
Is this code available in another repo? What license is that code under? I thought StreamCompanion was under the GPLv3, is that also true for this code?

**Comment by Piotrekol** [comment]
No, that code is not public. It might become available once osu!lazer becomes main osu client

**Comment by llllllllll** [comment]
So what is _that_ code licensed under? I thought I was installing a GPLv3 project but it's actually a proprietary blob with obfuscated source that kills itself under a debugger. That's sort of a bait and switch, no? What is the reason for going to such lengths to hide the behavior of a supposedly GPL project?

**Comment by Piotrekol** [comment]
https://osu.ppy.sh/community/forums/topics/209616?start=5068563
```
I'm still keeping SC obfuscated because of one class that if modified a little I believe it could allow for.. stuff
If that actually isn't a concern and someone from staff notifies me about this,
 it'll be pushed to github and it won't be obfuscated anymore.
```
Since then that one class became whole lib for reading osu! memory, but point still stands.

**Comment by llllllllll** [comment]
Did you consider asking peppy about this? https://twitter.com/ppy/status/968361420806148098. 
You are not the only one to write code using ReadProcessMemory, 2 seconds of googling reveals: https://github.com/aixxe/osu-relax. If anything, the fact that you are pulling in the symbol for WriteProcessMemory concerns me because I cannot see how it is being used, and it seems like you should only need read permissions on the osu! process to find the beatmap id and mod mask.

I think you should mention somewhere in the readme that this actually requires proprietary code and cannot be built from source.

**Comment by Piotrekol** [comment]
>cannot be built from source. 

It can be build from master branch without problems, it'll rely on MSN output(and thus no mods or live map data).
>WriteProcessMemory

Fair enough, there's some "legacy" code that never got used. This call is used in one function that never gets executed. It'll be removed(WriteProcessMemory import) in the next release.

**Comment by llllllllll** [comment]
The software as distributed to me cannot be built from source. I am not free to modify the program to do computing as I wish. Saying that this is GPL code is misleading at best. Also, scare quoting "legacy" in the context of WriteProcessMemory doesn't instill a ton of trust...

**Comment by Piotrekol** [comment]
License will be changed to MIT along with information that not all code used in application is avaliable in this repository in the next release.
And quotes might have been unnecessary, I have a bad habit of doing that.

**Comment by llllllllll** [comment]
Given that peppy doesn't seem to mind this code existing, why not release it? I feel bad for rewriting this given that you have already gone through all of the work; but I don't want to add a binary blob to my project.While you haven't made it easy, I see that you are just scanning the osu! process memory space looking for the root node of some structure, you then do some pointer chasing to find a structure which at least contains the beatmap id and the time. If you would feel more comfortable, maybe we can talk about this privately?
