### ISSUE TITLE
add option to remove decimals from live tokens

### ISSUE THREAD

**Issue by NitroBTW** [Piotrekol/StreamCompanion#181]
pretty self explanitory, i would like to not have decimal values in the live pp count using the obs plugin

**Comment by Piotrekol** [comment]
change it in tokens preview or in output pattern:
1. ![uV5shgpU7k](https://user-images.githubusercontent.com/4990365/91084458-50757780-e64c-11ea-9e88-a160122f45fd.gif)
2. ![sZJ0Q6uElL](https://user-images.githubusercontent.com/4990365/91084904-f45f2300-e64c-11ea-9da2-cc84beef6bea.gif)

**Comment by NitroBTW** [comment]
thanks Sent from Mail for Windows 10 From: Piotr PartykaSent: 24 August 2020 20:02To: Piotrekol/StreamCompanionCc: NitroBTW; AuthorSubject: Re: [Piotrekol/StreamCompanion] add option to remove decimals from live tokens (#181) change it in tokens preview or in output pattern:—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
