### ISSUE TITLE
ingame overlay broken???? or is there even one?

### ISSUE THREAD

**Issue by JakeNotSeen** [Piotrekol/StreamCompanion#188]
uhh so yeah recently i had a problem with the counter, and it is that the ingame overlay wont work, i am no streamer or whatever i just want it because i feel like it, but thats besides the point, im trying to get the ingame overlay to work, but whenever i play a beatmap, there is no "counter" seen, pls help

**Comment by Piotrekol** [comment]
This should help
https://github.com/Piotrekol/StreamCompanion/wiki/8.-Ingame-overlay-display
