### ISSUE TITLE
Add TCP socket output

### ISSUE THREAD

**Issue by Nodebuck** [Piotrekol/StreamCompanion#19]
Output to a TCP socket would be great for usage of the data in other projects without writing your own memory reader.

I'd like to use the data from a node.js script to create an animated web-based OBS overlay.

**Comment by Piotrekol** [comment]
Sure, no problem.
What data and in what frequency do you expect to get via this method.
I'm thinking that 2 sockets at minimum would be required: one for data that is map-dependant(so data sent only when map changes) and other for live map data(several times a second when playing/watching)

**Comment by Nodebuck** [comment]
My idea would've been to add a checkbox to enable tcp socket output for a pattern and then just send a packet every time the value changes. Optional settings to change IP and port would go into the "General" tab.

The packets could be UTF-8 JSON strings which are formatted like this:

    {
        "name": "np_listening",
        "value": "Listening: Panda Eyes - ILY"
    }

**Comment by Piotrekol** [comment]
So implemented... kinda
At start SC will expect to have server already ready to accept connections on 2 ports- one for regular patterns, and other for patterns that contain "live map tokens". 
SC is not reconnecting on any socket connection drop, so in case you need to restart your application you'll also need to restart SC. I'm not sure if I want to handle re-connections on some random users PC that are never going to use this feature, so most likely I end up adding on/off toggle for tcp before next release and then actively look for connection all the time.

Default ports are 7839 and 7840 and are changeable along with IP to bind in SC config file

C# code that was being used as test output:
```csharp
static void Main(string[] args)
{
    TcpListener listener = new TcpListener(IPAddress.Parse("127.0.0.1"), 7840); 
    listener.Start();

    TcpClient newClient = listener.AcceptTcpClient();
    BinaryReader reader = new BinaryReader(newClient.GetStream());

    while (true)
        Console.WriteLine(reader.ReadString());
}
```

**Comment by Piotrekol** [comment]
Sorry for the delay.
In the next release You'll be able to enable/disable TCP output at the bottom of the "Output patterns" tab(renamed "Map formating")
To change default port and ip you'll still need to manually modify settings in SC folder. 
I'll add tab for TCP output in wiki later.

**Comment by Nodebuck** [comment]
Sounds amazing, looking forward to the release!

**Comment by Nodebuck** [comment]
It's great and really responsive, I fiddled around with WebSockets to send the data to a browser instance and it works great, there's virtually no latency as seen here http://ndb.moe/NWP.mp4

Thanks so much for this, I might make a modular web-based overlay for OBS with an animated pp counter, difficulty graph, progress bar, beatmap cover, etc.
