### ISSUE TITLE
OBS lag while using the program

### ISSUE THREAD

**Issue by Futtomy** [Piotrekol/StreamCompanion#198]
Basically my OBS recording starts buffering whenever I open stream companion and doesn't stop until I close OBS and stream companion and reopen OBS. The game runs fine just the OBS recording and preview. Example Here: https://youtu.be/E2mEJJJmwSs

**Comment by Piotrekol** [comment]
check cpu usage of SC while this is happening.
check if mods in song selection are reflected in Tokens preview (`!mods!` token) 

mods issue is a known one(since yesterday) that seems to be happening on some pcs.

**Comment by Piotrekol** [comment]
try again with the latest build

**Comment by Futtomy** [comment]
CPU of SC never goes above 5% in my testing. It could be caused by the OBS plugin since I use it quite a bit for my main scene on OBS.

Mods in song select and in-game seem to be fixed after the latest build (I was having the same issue a while back with it not detecting mods and just displaying no-mod information)

**Comment by Piotrekol** [comment]
> It could be caused by the OBS plugin
instead of speculating go ahead and try removing obs plugin from your obs and seeing if issue persists

**Comment by Futtomy** [comment]
OBS runs like normal with the plugin removed and SC open.

**Comment by Piotrekol** [comment]
that's weird. There was no one else since the introduction of obs plugin with this issue, and it hasn't changed since release. 

Just to double-check: does the problem return once the plugin is added to obs again?
Make sure that it works as expected first without the plugin(doesn't lag) and add the plugin again without restarting osu! or Stream Companion

**Comment by Futtomy** [comment]
Yes the problem returns when the plugin is added back. If this helps the problem started when v200916.18 was released. Video: https://youtu.be/DrCmnbUM0JU

**Comment by Piotrekol** [comment]
without plugin obs uses ~2% of cpu, but with it around ~9%... there's something wrong going on here for sure 😅 . 
Does the issue persist if you use this SC version? https://github.com/Piotrekol/StreamCompanion/releases/download/v200813.17/StreamCompanion.Setup.exe

For me to try to reproduce this I'll need:
obs version
SC version(assuming current release)
your SC settings.ini file (can be via DM on discord https://discord.gg/N854wYZ )
what `SC source name`s are you using in obs

**Comment by Futtomy** [comment]
Yes OBS continues to lag when that version is in use. Glad to know it's not just my fault

OBS: Version 25.0.8
SC: Latest (200919.17)
The settings.ini file I can send as soon as I'm done typing this (Futtomy#5238 on discord)
The OBS Source names are the same as the pattern names you put into OBS

**Comment by Piotrekol** [comment]
in that case SC version has nothing to do with your problem 
> the problem started when v200916.18 was released.

version I linked was before one mentioned. You must have done(or windows?) something else in the meantime to cause this. 
tested just now with your settings file and all patterns included in obs + 2 invalid ones - no issues whatsoever.

I doubt I can help any further if earlier versions are also manifesting this problem for you right now.

**Comment by Futtomy** [comment]
I just attempted to reinstall OBS and that fixed the issue so it must have been something to do with OBS in general. Thanks for your help :)
