### ISSUE TITLE
Crash and then  error report crash

### ISSUE THREAD

**Issue by Stekeblad** [Piotrekol/StreamCompanion#2]
Made StreamCompanion crash, don't know how but the error is below. My Windows is in swedish and thats why some parts of the error message is not in english. Then I clicked on a copy and open error report button it crashed again with a continue or quit choice, I choose continue and it just closed.

```
Kapaciteten var mindre än den aktuella storleken.
Parameternamn: value   vid System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   vid System.Collections.Generic.List`1.set_Capacity(Int32 value)
   vid System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   vid #=qubp_ftX5CIKdcvfJ8DB6x5S1vkbcbhpeAZN2PaV062N02k8rOb9kMGwZ_ksHIqrM.#=qvX5$77kLeJt5fCyQU3p6MA==(IntPtr #=qyjfTV$qjtfzuw7VQcS_vZQ==)
   vid #=qubp_ftX5CIKdcvfJ8DB6x5S1vkbcbhpeAZN2PaV062N02k8rOb9kMGwZ_ksHIqrM.#=qM3qjRRbJSxJfJADMX4jtBg==(#=qrAxoc1jPEOgxIoJa_DkyfQ== #=qIX76GL1gKSPBFl2hSXUkqg==)
   vid #=qubp_ftX5CIKdcvfJ8DB6x5S1vkbcbhpeAZN2PaV062N02k8rOb9kMGwZ_ksHIqrM.#=ql6MeURXzMB_4_D4bVOWvpp4eHLrtco6fUg3MoMV4z8g=.#=qxKeOwuTmEQS6nOsMADk$vQltsNqfS3QQXIbxbEE3XiE=()
   vid System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   vid System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Piotrekol** [comment]
What osu! version are You using(fallback,stable,beta,CE)?
Was it Your first time using this version of StreamCompanion?

**Comment by Stekeblad** [comment]
Osu! version: b20160525.2 (Stable)
StreamCompanion v 160523.12
Downloaded StreamCompanion a few days ago and tried it and worked then, yesterday it worked for a song or two maybe and then I probably did something because during playing a song I noticed a error message half-hidden behind Osu with the error message above.

**Comment by Piotrekol** [comment]
This error couldn't have happened in the middle of the play(as it is tied to startup routine)
I've found and fixed this issue in the next release, no public commits for this one.
