### ISSUE TITLE
Huge amount of handles

### ISSUE THREAD

**Issue by LosTigeros** [Piotrekol/StreamCompanion#20]
After some time of having StreamCompanion running in background, the number of handles increases alot!
Maybe this is some sort of memory leak or something else wrong?

When StreamCompanion is running in background
![StreamCompanion in background](https://user-images.githubusercontent.com/6253928/37117710-43a60332-2252-11e8-8a31-bc3a26d9b5eb.png)

After closing StreamCompanion
![StreamCompanion closed](https://user-images.githubusercontent.com/6253928/37117767-6c070e0c-2252-11e8-8e9d-3839f7d6c990.PNG)

**Comment by Piotrekol** [comment]
I can reproduce, I've checked v180127.17 if it also "spams" with handles and no, but 2 versions following it does, with pointed me towards memory code.
This is now fixed(I've been opening new handles to read from osu! process each time...)

Expect release in the weekend.
