### ISSUE TITLE
Click counter score saving issue

### ISSUE THREAD

**Issue by cemoral** [Piotrekol/StreamCompanion#200]
https://github.com/Piotrekol/StreamCompanion/issues/151#issue-597189078 seems not fixed. İssue is explained below.

https://drive.google.com/file/d/115u5s2yO41V3_XkSC-gVWeOw0EqJEzJH/view?usp=drivesdk

**Comment by Piotrekol** [comment]
Start SC while holding ctrl & shift (or manually enable console & debug logging) and see what appears in the logs at the shutdown (logs will be saved in SC `Files/Logs` directory)

**Comment by cemoral** [comment]
See https://drive.google.com/file/d/116RIo2X-l_DpB_OGLqVGSEEWKSmMRPBb/view?usp=drivesdk

**Comment by Piotrekol** [comment]
`WDAGUtilityAccount` please for the love of god run it under normal user account.

**Comment by ohabu** [comment]
[2020-09-20.txt](https://github.com/Piotrekol/StreamCompanion/files/5252280/2020-09-20.txt)
Is my log useful for you? Unfortunately i have lazer installed on this computer.

**Comment by Piotrekol** [comment]
your logs are missing some lines that I would expect to appear at startup/shutdown.
try again using this build https://ci.appveyor.com/api/buildjobs/g9jt1o0rwd4dbsy6/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe

**Comment by ohabu** [comment]
[2020-09-20.txt](https://github.com/Piotrekol/StreamCompanion/files/5252347/2020-09-20.txt)
Okay, now i tried a few things. When i hit buttons and open the click counter tab in settings log, this line comes up > "[        ClickCounter] - Saved: 7,7; RM:0 LM:0" . But still the same output : No save on exit unless you open the tab.

**Comment by Piotrekol** [comment]
try again... Stream Companion was configured to ignore all errors on exit, big oof.
https://ci.appveyor.com/api/buildjobs/8vbd7ff3mw7116io/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe

**Comment by ohabu** [comment]
[2020-09-21.txt](https://github.com/Piotrekol/StreamCompanion/files/5255861/2020-09-21.txt)
oof.

**Comment by Piotrekol** [comment]
that seems to have changed exactly nothing... not what I expected. Lets wait for @cemoral to post his log before proceeding...

**Comment by ohabu** [comment]
Actually, an error window popped up on exit. What's the debug output on your end?

**Comment by Piotrekol** [comment]
Now that I checked, there was indeed an error reported. Still thinking why it hasn't saved in log file tho.
Yet another build should be available shortly there https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/35320946/artifacts

**Comment by cemoral** [comment]
OfffSee
[2020-09-21.txt](https://github.com/Piotrekol/StreamCompanion/files/5256033/2020-09-21.txt)

**Comment by Piotrekol** [comment]
@cemoral please test using build provided above your message

**Comment by cemoral** [comment]
It seems working
[2020-09-21.txt](https://github.com/Piotrekol/StreamCompanion/files/5256105/2020-09-21.txt)

**Comment by ohabu** [comment]
@Piotrekol you mean me?
I had SC and osu! installed before and uninstalled osu! but SC, that's why it's already initialized. I can confirm it works as intended now.
[2020-09-21.txt](https://github.com/Piotrekol/StreamCompanion/files/5256188/2020-09-21.txt)
