### ISSUE TITLE
livepp_hits problem

### ISSUE THREAD

**Issue by kappasa** [Piotrekol/StreamCompanion#205]
only the miss count is working as intended on the output for the OBS plugin.
![osu!StreamCompanion_pi2AEjLlVj](https://user-images.githubusercontent.com/22474177/94092575-17504300-fe56-11ea-8c51-df6488754f7c.png)

**Comment by kappasa** [comment]
I fixed after looking up token format lol, probably some update changed the format and broke it, should still be fixed for idiots that cba to learn it though.

**Comment by Piotrekol** [comment]
this is already accounted for in default patterns, I'm assuming you upgraded from older build and haven't reset/updated your patterns since.
https://github.com/Piotrekol/StreamCompanion/blob/master/osu!StreamCompanion/Code/Modules/MapDataParsers/Parser1/MapDataParser.cs#L75-L80
