### ISSUE TITLE
problems with livepp_ur on replays

### ISSUE THREAD

**Issue by SonGokuPL** [Piotrekol/StreamCompanion#209]
(Version: v200926.18)

After this update livepp_ur doesn't work while watching replays, but still works when I play a beatmap.
Maybe it's not a big problem for most people but I used this while recording my replays and it's bad to not have it now :/

**Comment by Piotrekol** [comment]
Read the latest changelog, especially bolded point 2 in `Added` section.

**Comment by Piotrekol** [comment]
Reopen if the problem still persists.
