### ISSUE TITLE
Allow ingame overlay on cuttingedge

### ISSUE THREAD

**Issue by kaimuu** [Piotrekol/StreamCompanion#210]
Currently the ingame overlay only works on stable and doesn't on cuttingedge. I don't think there should be any big issues to add compatibility for cuttingedge and it would help many people like myself who never switch to stable and prefer cuttingedge.

**Comment by Piotrekol** [comment]
[it does work on cutting edge](https://user-images.githubusercontent.com/4990365/95432787-66ff3600-094f-11eb-861a-3c6531a4075d.png), take a look here https://github.com/Piotrekol/StreamCompanion/wiki/8.-Ingame-overlay-display
