### ISSUE TITLE
How do i uninstall streamcompanion?

### ISSUE THREAD

**Issue by Pingwiniarz** [Piotrekol/StreamCompanion#216]
I don't know how to uninstall streamcompanion, I tried everything I can, even uninstalled osu and further in my settings you can see the msn live setting

**Comment by Piotrekol** [comment]
`msn live setting` is osu setting. SC doesn't alter osu files in any way.

**Comment by Pingwiniarz** [comment]
ive got an error and i cannot launch sc but i restarted my pc.
thanks for reply.
