### ISSUE TITLE
How to remove backround in the /web overlay

### ISSUE THREAD

**Issue by leofancyngrok** [Piotrekol/StreamCompanion#223]
![issue stream companions - Imgur](https://user-images.githubusercontent.com/38032102/98695565-10807f80-2373-11eb-8fe3-81bdf1b125f0.png)
i want to remove the backround when i switch maps to a transparrent backround on the web overlay that you will see in the file i attached.

how do i make it transparrent and not the backround of the beatmap?

**Comment by Piotrekol** [comment]
remove these 2 lines in index.html of that overlay
https://github.com/Piotrekol/StreamCompanion/blob/master/webOverlay/overlays/SC_Map%20Overlay/index.html#L21-L22
