### ISSUE TITLE
stream companion crashes as soon as i play an osu map

### ISSUE THREAD

**Issue by KubaPlaysHD** [Piotrekol/StreamCompanion#225]

**Comment by Piotrekol** [comment]
is it a hard crash? (does it kill itself w/o showing any information?) If not please provide the full exception text, that's shown in the error window shown before closing SC.

also, you can try using latest pre-release build https://ci.appveyor.com/api/buildjobs/c4diw4dcthjqa1c3/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe

**Comment by KubaPlaysHD** [comment]
[image: image.png][image: image.png]
Error messages

**Comment by Piotrekol** [comment]
you might want to retry that (and post exception text instead of screenshotting it)

**Comment by KubaPlaysHD** [comment]
Post exception text?

**Comment by KubaPlaysHD** [comment]
UnauthorizedAccessException: Access to the path 'C:\Program Files
(x86)\StreamCompanion\Files\BG.png' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at
BackgroundImageProvider.BackgroundImageProviderPlugin.InternalCreateTokens(IMapSearchResult
map, CancellationToken cancellationToken, Int32 retryCount)
   at
BackgroundImageProvider.BackgroundImageProviderPlugin.CreateTokensAsync(IMapSearchResult
map, CancellationToken cancellationToken)
   at
osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.CreateTokens(IMapSearchResult
mapSearchResult, CancellationToken cancellationToken)
   at
osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.<>c__DisplayClass10_0.<<ProcessMapResult>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at
osu_StreamCompanion.Code.Core.Maps.Processing.MapStringFormatter.<ConsumerTask>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at
System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object
state)
   at
System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object
state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

 is this what you mean?

**Comment by Piotrekol** [comment]
Workaround added in 17ae5137672466c24ddaa8cf2e5ef5dc4f4c5c28. To fix this you should either reinstall SC or remove BackgroundImageProvider.dll from Plugins folder(note that it will restore itself on each update)
