### ISSUE TITLE
Combo and acc display

### ISSUE THREAD

**Issue by Veirel** [Piotrekol/StreamCompanion#226]
Hello,

I was wondering if there was a way to have the stream companion only the display the combo and the accuracy. Here is an example of what it looks like: 
![Example01](https://user-images.githubusercontent.com/75441664/101060285-41f8ff00-355d-11eb-8b44-2fd4a8f6c080.jpg)

I asked the streamer how he did it and he said it was done with the osu! stream companion. I searched a bit to find a way to display the combo/acc and nothing else but I couldn't. I am very new to this program so any help would be appreciated.

Have a good day

**Comment by Piotrekol** [comment]
create `Output pattern` with uses 2 `tokens`: acc and combo eg.
```
!acc!% | !combo!x
```
For a list of all usable tokens, see `Tokens preview` tab in settings.

if you want it displayed only when playing/watching, set save event of that `Output pattern` to `Playing & Watching`

**Comment by Veirel** [comment]
> create `Output pattern` with uses 2 `tokens`: acc and combo eg.
> 
> ```
> !acc!% | !combo!x
> ```
> 
> For a list of all usable tokens, see `Tokens preview` tab in settings.
> 
> if you want it displayed only when playing/watching, set save event of that `Output pattern` to `Playing & Watching`

**Comment by Veirel** [comment]
oops didnt mean to close. Ty! ill give this a try.
