### ISSUE TITLE
Feature Request: !mapFC! and !currentlyFC! tokens.

### ISSUE THREAD

**Issue by ggtylerr** [Piotrekol/StreamCompanion#229]
Basically just 2 tokens which would be really useful if someone is trying to FC a map.

`!mapFC!` would show how much combo you'd need in order to reach an FC on that map. (Couldn't think of a better name.)

`!currentlyFC!` would show whether or not you're currently on a FC. (Could be True or False, or a 1 or 0 if you need it to work with math or something like that.)

**Comment by Piotrekol** [comment]
both of these are doable but need better names.
mapFC/currentMaxCombo - I guess currentMaxCombo could be the name, but where do you plan on using these? this could be provided instead as a `comboLeft` token containing the remaining combo in the map. That way I think this would be more useful when used in combination with other tokens (note that you can use `{combo+comboLeft}` format in output patterns to essentially get the currentMaxCombo value)

currentlyFC - currentlyFcing ? can't come up with better name myself.

**Comment by Piotrekol** [comment]
`currentlyFC` can be calculated by checking if both misses and sliderbreak values are 0
