### ISSUE TITLE
If using a Songs directory outside of osu!'s directory, !OsuFileLocation! will return wrong path

### ISSUE THREAD

**Issue by avail** [Piotrekol/StreamCompanion#23]
In my example, I have my songs directory in `G:\Games\osu!old\Songs`, and run my osu! from `G:\Games\osu!`

!OsuFileLocation! returns e.g. `G:\Games\osu!\Songs\420390 Machico - fantastic dreamer\Machico - fantastic dreamer (Rizia) [Fantasy].osu` instead of `G:\Games\osu!old\Songs\420390 Machico - fantastic dreamer\Machico - fantastic dreamer (Rizia) [Fantasy].osu`

**Comment by Piotrekol** [comment]
[oops line](https://github.com/Piotrekol/StreamCompanion/blob/e188f8a952c807e7fac56b97641c3739bc6dd88a/osu!StreamCompanion/Code/Modules/MapDataReplacements/Map/MapReplacement.cs#L30) 
Fix will be in the next release

**Comment by avail** [comment]
❤️
