### ISSUE TITLE
Stream companion wont let me use the Ingame check box in output patterns

### ISSUE THREAD

**Issue by Zeeco-rgb** [Piotrekol/StreamCompanion#231]

**Comment by Piotrekol** [comment]
little late but any more details? 
does the "enable/showingame" checkboxes not appear at all?
does the ingame overlay report an error while starting? 
not much to work with...

**Comment by Zeeco-rgb** [comment]
I got it working. Nothing was dissappeared, the whole system to enabling
the stuff to get the ingame stuff was confusing. nothi else
