### ISSUE TITLE
Freezes ingame

### ISSUE THREAD

**Issue by kappasa** [Piotrekol/StreamCompanion#238]
I'm experiencing constant freezes in osu! that go away after terminating streamcompanion, I noticed that the cpu usage tends to go abnormally high which I assume is the primary cause of this.

**Comment by Piotrekol** [comment]
abnormally high.. meaning? SC is expected to have CPU usage spikes when pre-processing beatmap for pp & strains calculations, but that should never happen during actual gameplay.
Does disabling everything in Map matching settings make this any better? (note that this is not a solution as it will disable a big chunk of SC tokens, including pp)

**Comment by kappasa** [comment]
Usually SC doesn't go over 5% when playing, however, in some rare instances it tends to goes over 50%.
There is some maps that SC fails to read the bpm and pp values of, maybe it gets stuck trying to read those causing strain or something? it happens fairly rarely and I'm not sure how to replicate it.
And yeah I use a bunch of tokens so disabling those would probably fix it, but that's the whole point I use SC for :P.

**Comment by Piotrekol** [comment]
> Usually SC doesn't go over 5% when playing

That's still higher than expected, but depending on what cpu you have I guess this could be the case. Personally, I'm getting around 2\~3% usage with visualizer enabled and ~0,2% with it disabled while playing.

You still haven't answered my question `Does disabling everything in Map matching settings make this any better?`
ignore your use case, for now, we want to know if it affects cpu usage in any major way.
