### ISSUE TITLE
Incorrect map length on maps that end with slider or spinner

### ISSUE THREAD

**Issue by Raitoningu-D** [Piotrekol/StreamCompanion#239]
Said to be fixed in v200813.17, but I am observing this issue in latest version as well as from v200926.18 onwards. This was checked each time with a fresh install of StreamCompanion including deleting the settings.ini file.

Some examples of random songs where it happens:
![image](https://user-images.githubusercontent.com/12639308/105938967-5f090480-60ac-11eb-9df6-5ec042e0fd27.png)
![image](https://user-images.githubusercontent.com/12639308/105939033-7b0ca600-60ac-11eb-8011-d7d37e419eb2.png)
![image](https://user-images.githubusercontent.com/12639308/105939056-865fd180-60ac-11eb-9cc1-5fed8b67cbce.png)

**Comment by Piotrekol** [comment]
problem was with the overlay itself, not map length value SC is providing
