### ISSUE TITLE
pp calculator not updated to reflect HD rebalance

### ISSUE THREAD

**Issue by ceilingwaffle** [Piotrekol/StreamCompanion#24]
pp calculator still showing numbers from before the HD rebalance. I think the OppaiSharp reference needs to be updated? 

Cheers,
Waffle.

**Comment by Piotrekol** [comment]
I myself updated oppaisharp with HD changes so I am aware.
I had few problems with new ingame display in SC, but most of them are gone
now.
 I'll try to get that finally sorted out and push new release in a day or
two.
