### ISSUE TITLE
microsoft net issue

### ISSUE THREAD

**Issue by damianham420** [Piotrekol/StreamCompanion#240]
i updated my stream companion and now everytime i open it it says "To run this application, you must install .NET." and it has a button that leads to the download. ive downloaded it, restarted my computer, uninstalled it, reinstalled it, and repaired it and it still says that it needs downloaded. btw i downloaded the x64 because i am on a 64-bit system.
![asddsasaddsad](https://user-images.githubusercontent.com/59099396/107132602-761ad400-68ae-11eb-8a81-48df4e3acb63.PNG)

**Comment by Hakuriki-ko** [comment]
I had the same problem.
The workaround is to install x86 .net.
The release page clearly states that x86 should be installed, but the dialog when launching the application opens the x64 page.

Download x86 from here.
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.2-windows-x86-installer

**Comment by Piotrekol** [comment]
As noted in post above and in the release notes for the current SC release - SC requires x86 version of .NET5 runtime, regardless of what system you use.

**Comment by CheeseManFuu** [comment]
> As noted in post above and in the release notes for the current SC release - SC requires x86 version of .NET5 runtime, regardless of what system you use.

Please reference this in the pop-up then. As somebody who just had it before and had to update because I hadn't used it in a while I was confused until I had to come here. Having to download x86 .NET isn't the most intuitive thing for most users since a majority of programs ask for you to match x64 OSs with x64 libs and x32 with x86.

**Comment by Piotrekol** [comment]
it is already referenced in the update window - top of changelog provided in that window contains same text as on release page.
It is not possible to do anything else for previous SC versions.
