### ISSUE TITLE
osu! ingame pp counter not working

### ISSUE THREAD

**Issue by CoWeeb** [Piotrekol/StreamCompanion#242]
I can't see the osu! pp counter ingame I downloaded the plugin and I set it to opened it does not work

**Comment by Piotrekol** [comment]
I already said this on discord, but going to repeat myself: 
I believe the solution is to install vcredist, [for with ingameOverlay wiki was updated](https://github.com/Piotrekol/StreamCompanion/wiki/8.-Ingame-overlay-display#installation)
