### ISSUE TITLE
Shorten division results

### ISSUE THREAD

**Issue by MasterZitron** [Piotrekol/StreamCompanion#246]
Doing simple divisions gives the desired result, but its too specific. Is there a way to make it not show the full thing? Maybe only show 2-3 digits after the decimal
![image](https://user-images.githubusercontent.com/32692021/107699082-4eec4a00-6c94-11eb-88bb-5111b5d7b677.png)

**Comment by Piotrekol** [comment]
change it to `{geki/c300 :0.##}` to optionally show up to 2 decimals or `{geki/c300 :0.000}` to always show 3 decimals etc..
