### ISSUE TITLE
Application No Longer Opens

### ISSUE THREAD

**Issue by itzpigeon** [Piotrekol/StreamCompanion#247]
I've been using this program for quite a long time now, and I've seldom had any issue with the program once I figured out how it worked until recently. I'm not sure what changed or when, but after a recent update to the application, I am no longer able to run the program on my computer. Each time I attempt to open the program, I am met with the same error message:
"To run this application, you must install .NET.
Would you like to download it now?"
I know it may sound like a simple fix, as I thought it should be too, but when I click to install .NET, I'm taken to the normal windows page for installing .NET 5.0 Runtime, which I've attempted to uninstall and reinstall at least 5 times now. Every single time the installation works with no issue but when I try to open StreamCompanion.exe, I am still met with the same error message telling me .NET needs to be installed. 

I haven't tried to uninstall and reinstall StreamCompanion yet to see if that might fix the issue, since I don't want to lose all of my settings for my beatmap overlay and now playing portions of the program. If there is any way of preserving these settings after a fresh reinstall however, then I'd be willing to try this but otherwise I'm at a loss as to how I should fix this.

**Comment by miahz123** [comment]
Try downloading [this one](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.2-windows-x86-installer)

I had the same issue, but the program requires the x86 version of it, although I'm running a x64 system.

**Comment by itzpigeon** [comment]
Ok wow that seemed to be the solution. I have a x64 operating system so I never bothered to try the x32 version of .NET. That's pretty weird, but this does work so thank you for the help!
