### ISSUE TITLE
Osu overlay text alignment

### ISSUE THREAD

**Issue by LosTigeros** [Piotrekol/StreamCompanion#25]
It would be nice to have text alignment added to osu overlay so we could choose between `left`,`center`,`right`.

![image](https://user-images.githubusercontent.com/6253928/41237565-20e1b502-6d94-11e8-8f5a-83c34fb65c69.png)
It would look much better with center alignment.

**Comment by Piotrekol** [comment]
Sure, but not this week, next week earliest.
Requires both overlay dll and SC changes.

**Comment by LosTigeros** [comment]
Sure, take your time. No rush :D
