### ISSUE TITLE
PP values are incorrect

### ISSUE THREAD

**Issue by uwumeharder** [Piotrekol/StreamCompanion#250]
As the title says, the values for the PpIfMapEndsNow, osu_mSS-95PP aren't correct in comparison to those on live servers. Modded pp values also have this issue.

**Comment by Piotrekol** [comment]
Some values on live osu server might (still) not be recalculated, meaning that these scores will have old pp values. If you believe this is not the case here please provide examples - scores(map and playerName) and/or beatmaps
