### ISSUE TITLE
Need to install .NET but after installing it still doesn't work?

### ISSUE THREAD

**Issue by DragoBruder** [Piotrekol/StreamCompanion#254]
Yeah its pretty much the stuff in the title thats all.

Tried installing the newest and the "latest" latest preview (.NET 6 instead .NET 5).

Both doesn't work to run osu!companion. PC got restarted.

**Comment by Piotrekol** [comment]
![image](https://user-images.githubusercontent.com/4990365/108625707-96b96100-744c-11eb-998c-cdb07f713f72.png)
https://github.com/Piotrekol/StreamCompanion/releases
https://github.com/Piotrekol/StreamCompanion/issues/240#issuecomment-774656729
