### ISSUE TITLE
Cant Install Stream Companion

### ISSUE THREAD

**Issue by Machiron** [Piotrekol/StreamCompanion#255]
I dont know what's wrong but I cant install StreamCompanion, after the create shortcut to Desktop, it'll pop up the Error window: 
"The drive or UNC share you selected does not exist or is not accessible. Please select another. "
I tried to install on other hard drive and give it administrator right but it keep that error, I  try the previous release but it did the same thing.

Note: I'm using Windows 10 Pro 20H2 and I installed .NET5(x86) runtime before installing like your guide.

![image](https://user-images.githubusercontent.com/75469522/108854339-54457f00-761a-11eb-8662-41698c7affd2.png)

**Comment by Piotrekol** [comment]
Do you have any network drives on your system?
where is your osu/SC installed?
are you using custom osu! songs directory?

**Comment by Machiron** [comment]
I'm using an Wifi external Pci-e card, I install its driver so it's work normally, no issue since the time I put it in.
I put osu! folder in the different HHD tho, but I find out that move the SC.exe in the same directory with osu! folder or not it'll not fix the problem.
And of course I tried times by re-download, re-install and always directly click the ".exe" file, even run is as administrator some time but it still go the same error.
