### ISSUE TITLE
New versions add ms to osu! peripherials

### ISSUE THREAD

**Issue by EnanoFurtivo** [Piotrekol/StreamCompanion#26]
First of all thanks for your time. Now onto the subject, I used to use osu! stream companion until about a month ago bc i didn't get any time to stream since then. So i decided to update, after that i realized my cursor was moving slightly off. Then checked my ms and i had 1.50 ms when i usually have 0.40 ms. It might not seem like much but im actually quite sensible to the delay since i have played for a really long time on 0.4. Also i dont stream every time i play osu! so changing between 1.5 and 0.4 ms is quite frustrating since i tend to miss bc i cant get used to a delay again.

I dont really care if this is solved or not but hey it would be a nice touch. I dont know if im sure but i think it could be the RTPP that was implemented recently, since i had the old RTPP that was used before it was implemented on this app and that one added msto my osu! so i hat to uninstall it, again im not really sure if it could be that since i have it turned off.

when trying to find the problem i tried obs running without stream companion and no ms were added so its not obs. These are my configs:

![screenshot_275](https://user-images.githubusercontent.com/31115763/41631924-bde9f560-740d-11e8-8e02-b97b5b5fbf41.png)
![screenshot_276](https://user-images.githubusercontent.com/31115763/41631925-be17d6a6-740d-11e8-99aa-9f3f6fbf2120.png)
![screenshot_277](https://user-images.githubusercontent.com/31115763/41631926-be44ed76-740d-11e8-8dc8-bc8495d38b5c.png)
![screenshot_278](https://user-images.githubusercontent.com/31115763/41631927-be700da8-740d-11e8-9286-1451337323c5.png)
![screenshot_279](https://user-images.githubusercontent.com/31115763/41631928-be9a87cc-740d-11e8-8563-24172ebac74e.png)
![screenshot_280](https://user-images.githubusercontent.com/31115763/41631929-bec308aa-740d-11e8-8089-dacaec13c090.png)
![screenshot_281](https://user-images.githubusercontent.com/31115763/41631930-befd7896-740d-11e8-8c26-0d64bb51f81a.png)

**Comment by EnanoFurtivo** [comment]
btw i do have MSN turned on inside osu!

**Comment by EnanoFurtivo** [comment]
Ijust discovered it actually was OBS so im colsing the issue :P

**Comment by Piotrekol** [comment]
Glad you figured this out.
And to clarify- SC is not using RTPP to get osu data. I have my own
implementation of it.
