### ISSUE TITLE
Live visualizer doesn't always update

### ISSUE THREAD

**Issue by RealCyGuy** [Piotrekol/StreamCompanion#260]
Changing the song to [1925](https://osu.ppy.sh/beatmapsets/39714#osu/126401) doesn't update the live visualizer. These are the logs for changing to another song:
```
[Deb] 6:35:44 PM [  MapStringFormatter] - Received event: { eventType = MapChange, mapId = 180841, raw = nana(Sevencolors) - Chameleon [Hard], hash = 3a723cfb1b0d2ab6e09f6338e2e4b223, playMode = Osu, sourceName = OsuMemory }
[Deb] 6:35:44 PM [OsuMemoryEventSource] -       Got mods from memory: None(0)
[Deb] 6:35:44 PM [   MainMapDataGetter] -       Found data using "rawString" ID: 180841
[Tra] 6:35:45 PM [LiveVisualizerPlugin] - Updating live visualizer window
[Tra] 6:35:45 PM [LiveVisualizerPlugin] - Finished updating live visualizer window
```
And this is when I change to 1925:
```
[Deb] 6:35:51 PM [  MapStringFormatter] - Received event: { eventType = MapChange, mapId = 126401, raw = Nobunaga - 1925 [Hard], hash = d833a5d6513c6d397b54ca190f4be52f, playMode = Osu, sourceName = OsuMemory }
[Deb] 6:35:51 PM [OsuMemoryEventSource] -       Got mods from memory: None(0)
```
It doesn't say `found data using "rawString" ID: (id)`

**Comment by Piotrekol** [comment]
Can't reproduce:
move SC beatmap cache `StreamCompanionCacheV2.db` somewhere else and let SC rebuild it. If that fixes it I'd like you to send me link to that file either here or via discord https://discord.gg/N854wYZ
if that still doesn't work test with the newest SC version

**Comment by RealCyGuy** [comment]
Yeah, it did fix it. Link to cache database: http://transfer.sh/7LshB/StreamCompanionCacheV2.db

**Comment by Piotrekol** [comment]
Forgot to respond: didn't find anything _wrong_ in that database. This is most likely caching issue that regressed after removing checksums of beatmap data. That will be re-added properly in the next release(old hashing method was flawed)
