### ISSUE TITLE
PP stays at zero upon entering song in Live Visualizer

### ISSUE THREAD

**Issue by Shugii** [Piotrekol/StreamCompanion#264]
Simulate pp while listening is checked, and the pp value changes in lobby whilst listening. Additionally the PP will live-update based upon my play, but after awhile (1h+) it will just remain at 0 upon entering any song and will no longer update while playing.

I should mention restarting osu! and restarting SC will fix the problem but I don't want to have to restart it every hour in order to make it work again.

**Comment by Piotrekol** [comment]
this is either fixed in the next release or it will result in an error to be thrown explicitly instead of updates just dying
[`952d777` (#257)](https://github.com/Piotrekol/StreamCompanion/pull/257/commits/952d77705430374dc82ddbc83066f0b8d271da2d)

I encountered this once in current release
