### ISSUE TITLE
.NET popup won't go away so I can't launch SC

### ISSUE THREAD

**Issue by uwumeharder** [Piotrekol/StreamCompanion#266]
I downloaded .NET x86 after updating, but the popup for me to install .NET doesn't leave. I can't launch SC anymore. Is this a bug, or did I do something wrong?

**Comment by MentSB** [comment]
Happens something similar to me, I try to update but after it downloads it says that this version of SC uses .NET5 x86 and tells me to install it, even after I did. Although I can just close it and choose to not install the update and will function as normal (the previous version)

**Comment by Piotrekol** [comment]
there's an issue with SC updater with will be resolved with next release within this week.

until then if you want to use SC:
install both x86 and x64 .NET runtimes
uninstall SC
restart PC
install SC again

that's what worked for some users

**Comment by Piotrekol** [comment]
I forgot to mention, this is already fixed in the latest pre-release version of SC, so you might want to give that a go instead

**Comment by Zackattack092002** [comment]
I had this same issue with the version i used to be on, I uninstalled and downloaded v210314.18 and now SC doesn't give the .NET runtime box, but still refuses to open. Could this be something wrong with this version or did I miss a step somewhere?
