### ISSUE TITLE
wrong pp calculation

### ISSUE THREAD

**Issue by awen478** [Piotrekol/StreamCompanion#268]
website : https://i.imgur.com/L71Ksmq.png

PP calculator : https://osu.ppy.sh/ss/16321774/6d19
https://i.imgur.com/uPlTu63.png

Map : https://osu.ppy.sh/beatmapsets/971957#osu/2034983

**Comment by Piotrekol** [comment]
already fixed via https://github.com/Piotrekol/StreamCompanion/commit/5e0408006bd94762c54a56705502b7fb90248352
release with mostly bugfixes should appear within this week
