### ISSUE TITLE
won't download the software

### ISSUE THREAD

**Issue by Blazinganglez2** [Piotrekol/StreamCompanion#27]
i click the stream companion,exe file to download and everytime. (on goggle crome and firefox) it says download failed. i'm sure i'm clicking the right one but at one point it said virus detected.

**Comment by Piotrekol** [comment]
Something caused a massive spike in false-positive detections (try compiling yourself in release version and scanning output exe in virustotal, you should get some detections)
I'll spend some time figuring out what caused this today/tomorrow.

**Comment by Piotrekol** [comment]
https://www.virustotal.com/#/file/6b22f3112e7efbab8a712d63098c0f7529093586378ce7ead6ece63d265c88da/detection
I'm getting this from fresh winForm .net4 project named "osu!StreamCompanion"
...can someone explain what the is going on here?

**Comment by Molvou** [comment]
Yeah i can't install it either because my antivirus detects a trojan

**Comment by Piotrekol** [comment]
As I said before, I am aware of the sudden "trojan" detection, and I wasn't able to find out what causes it(manually removed majority of SC code- detection didn't change), and it isn't related to my PC specifically either(ruled that out by compiling on a friends PC- same story)

By the end of the week, I hope to both:

- [ ] finish this PR to "fix" this false-positive https://github.com/Piotrekol/StreamCompanion/pull/29 (this isn't intention of this PR, but it's a side effect that It'll provide)
- [ ] automate SC builds using AppVeyor.

This should resolve this "issue"...

**Comment by Piotrekol** [comment]
https://github.com/Piotrekol/StreamCompanion/releases/tag/v180630.12
