### ISSUE TITLE
Can't finish small test

### ISSUE THREAD

**Issue by Wildneko** [Piotrekol/StreamCompanion#270]
I tried to finishing this small test, but i already try until 10+ times and restart my pc 3 times, and it doesn't work
and it says : "Something went wrong (Mods : Omod). Maybe try again with another map?"
![scerr](https://user-images.githubusercontent.com/80520310/110932189-b6fa8280-835d-11eb-9304-4a70e07d87e8.PNG)

Is there someone can help this?

**Comment by Piotrekol** [comment]
Select mods that are requested in that window (HR,NR,DT,HD)

**Comment by Wildneko** [comment]
It works, thanks 👍
