### ISSUE TITLE
Small test doesn't want to work.

### ISSUE THREAD

**Issue by Soulixpog** [Piotrekol/StreamCompanion#271]
![image](https://user-images.githubusercontent.com/55710031/111905185-b42d1b00-8a4a-11eb-8610-63b66c93c43f.png)
It is frozen like this and no matter if i put the right mods and enable or disable the msn live ingame it doesn't change anything i tried multiple times uninstalling it and reinstalling it aswell.

**Comment by Piotrekol** [comment]
looks like osu! memory reading issue that seems to be affecting some users. Update to the newest pre-release version and try again https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/38313039/artifacts

Note that if this happens to work, gamemode detection will be broken on your PC (doesn't matter if you only play osu! mode)
