### ISSUE TITLE
.NET problem

### ISSUE THREAD

**Issue by Niwa2D** [Piotrekol/StreamCompanion#274]
I install the app and .NET and I launched Stream Companion. Then I came across an error saying I must install .NET. It doesn't say I have to install Framework or Core. Can someone help me resolve this issue please, if so that would be really nice. Thanks!
![image_2021-03-24_160056](https://user-images.githubusercontent.com/81328965/112375825-1e97c280-8cba-11eb-8957-12934fc9c15a.png)

**Comment by Piotrekol** [comment]
https://github.com/Piotrekol/StreamCompanion/issues/240#issuecomment-774656729
