### ISSUE TITLE
Cant Launch Stream Companion

### ISSUE THREAD

**Issue by username7461** [Piotrekol/StreamCompanion#275]
Whenever i am trying to launch osu!StreamCompanion.exe. An error keeps popping up as shown below:

![Screenshot 2021-03-27 171721](https://user-images.githubusercontent.com/50647214/112716287-661f8800-8f20-11eb-8aa4-92dfd91c5d55.png)

I make sure that i install x64 .net 5.0 runtime desktop as instructed but it was in vain. The error is still popping up for me.

**Comment by Piotrekol** [comment]
>  x64 .net 5.0 runtime desktop as instructed

there is no mention of x64 anywhere (either in this message, or in any release changelog)
see: https://github.com/Piotrekol/StreamCompanion/issues/240#issuecomment-774656729
