### ISSUE TITLE
Tokens work during Watching but some do not during Playing (100s, 50s, misses)

### ISSUE THREAD

**Issue by Yuwuyuwukowo** [Piotrekol/StreamCompanion#279]
v210330.17 (latest at this time) seems to have broken 100s, 50s, misses and some other tokens, to where they only update during replays and not during actual gameplay.

One of my replays:
![osu!_kG6uEMTdp0](https://user-images.githubusercontent.com/66982744/113110295-883d3280-91cc-11eb-9acb-3b0e59aad180.png)

Paused at beginning of same map (the 100s, 50s, and misses are stuck at what they were when I closed the replay):
![image](https://user-images.githubusercontent.com/66982744/113110376-9db25c80-91cc-11eb-96e1-b7ac47742070.png)

Starting a different map still doesn't change these tokens. Only another replay does.
Restarting osu and choosing a random map leaves these tokens at 0 the entire time.

I've done a fresh install of stream companion once with the settings config kept and once unkept. Reinstalled the in game and browser overlays as well.

Hoping this isn't just a weird issue only affecting me lol. Lmk if you need more info.

**Comment by Piotrekol** [comment]
Fixed via 9380ee8fe5ab9e4acb856e8e2becc937d19962e1 in v210331.17
