### ISSUE TITLE
Osu crashes immediately after updating to V210330.17

### ISSUE THREAD

**Issue by aliencaocao** [Piotrekol/StreamCompanion#280]
Whenever i am running StreamCompanion V210330.17, osu crashes within 3 seconds after being launched. When I launch without without running the software, everything goes normal. The previous version (v210314.18) works perfectly.
Installing the latest SteamCompanion (V210330.17) and the previous version of ingame overlay (v210314.18) immediately fix the issue for me. Thus I can be almost certain that the updated in game overlay is causing the crash

**Comment by aliencaocao** [comment]
v210412.08, v210402.17, v210331.17 just tested all 3 versions of ingame overlay - all crashes with exact same behaviour
the only combination I can get it to work is main program v210412.08 (latest to date) and v210314.18 ingame overlay. All in game overlays newer than that will cause an immediate crash. Able to reproduce 100% in more than 10 tries before and after restarting windows.

**Comment by Piotrekol** [comment]
Is there any reason you're using studio drivers instead of game-ready one? 
Not sure if that is the issue, but your configuration is pretty much same as mine except for GPU (2070S) & me running game-ready drivers

**Comment by aliencaocao** [comment]
Hi, thanks a lot for the advice. I was running MSI After Burner to monitor FPS, and I quitted it and installed latest version of screen overlay, and it no longer crashes. The problem was indeed with conflicting screen overlay. However, I still wish to monitor my system stats while gaming, so i would prefer to use back the old version of game overlay which works perfectly even with MSI After Burner. Maybe you could add 'do not run other screen overlay apps' into the tutorial on using it, and also mention that  in game overlay v210314.18 actually have no issue running with other screen overlay apps. I think this will help a lot other users. Great work there!

**Comment by Piotrekol** [comment]
this is actually what the recent change in overlay was supposed to fix, so I'll be looking into why it breaks with that specific MSI overlay.
