### ISSUE TITLE
StreamCompanion crashes after update

### ISSUE THREAD

**Issue by TMGame** [Piotrekol/StreamCompanion#281]
![image](https://user-images.githubusercontent.com/81740498/113258238-46aca480-92fe-11eb-98f3-0f049af40c31.png)

This is what happened when I updated the application to the latest version.

It's saying that its about the "osuOverlayPlugin" not initializing properly or something?

I'd be glad if anyone can help me here.

**Comment by Piotrekol** [comment]
if you haven't figured that already: you need to update your version of (text) overlay plugin after updating SC
