### ISSUE TITLE
StreamCompanion crashing very often and giving the same error report

### ISSUE THREAD

**Issue by sriracha-rice** [Piotrekol/StreamCompanion#282]
"There was an unhandled problem with the program and it needs to exit. Error report was sent to Piotrekol." This pops up very frequently, followed by this error report:
![streamcompanion](https://user-images.githubusercontent.com/73047092/113500614-2cc4ba80-94d4-11eb-864c-a44f89ff0149.PNG)

This has been a problem for about a month now. Is this something that is an issue only with me, and if so, what do I need to do to fix it?

**Comment by xdAlimant** [comment]
Having the same problem for about 2 weeks, couldn't find anything on it :(

**Comment by Piotrekol** [comment]
Already fixed in pre-release. will close once next release is published
