### ISSUE TITLE
Stream Companion doesn't detect .NET

### ISSUE THREAD

**Issue by HatsukuLive** [Piotrekol/StreamCompanion#283]
Whenever I launch SC I always get this error:

"To run this application, you must install .NET
The framework 'Microsoft.WindowsDesktop.App', version '5.0.0' was not found. "
I installed .NET latest version (5.0.4), didnt work. I tried using the exact version specified too (5.0.0) and it still isn't working.

**Comment by LittleSaya** [comment]
I meet with this problem too, I followed the alert and installed .NET 5, but it is still telling me to install .NET 5.

Actually I previously installed a .NET 5 SDK, but it couldn't detect that as well.

The "dotnet" is in the "PATH" environment variable.

![Annotation 2021-04-10 174746](https://user-images.githubusercontent.com/16049823/114265696-e2d45b00-9a24-11eb-803b-19751394bf86.png)

**Comment by Piotrekol** [comment]
https://github.com/Piotrekol/StreamCompanion/issues/240#issuecomment-774656729
