### ISSUE TITLE
hit counters not updating on replays

### ISSUE THREAD

**Issue by PatyYe** [Piotrekol/StreamCompanion#284]
The issue with #281 still happens to me. On replays and normal plays the counters are not updating.
Tried resetting the game, app, without resolving the issue.

Reenabled key overlay, issue remains.

**Comment by Piotrekol** [comment]
first: 281 is not related to this at all ??
second: works fine here on newest release so you'll have to provide more info.

Start SC with Ctrl and Shift pressed to show console with logs, are there any memory errors? 
Reproduce your issue few times with that console running and send the log file created in `Files\Logs` in SC install directory

**Comment by PatyYe** [comment]
Reason I mentioned 281 was due to the bug happening the same week after I updated it. 
It doesn't have any memory errors/reading errors till it starts loading one of the ' replays ' or just start playing it gives me the following error 10 times within a second:
[War] 20:30:38 [OsuMemoryEventSource] - Failed to read "Player.Score" memory value
[2021-04-12.txt](https://github.com/Piotrekol/StreamCompanion/files/6299014/2021-04-12.txt)

Running the game as admin/application as admin doesn't resolve it.
Attached the log file.

**Comment by Piotrekol** [comment]
did you try with multiple replays, or only one with SV2 enabled...?

**Comment by PatyYe** [comment]
Issues resides with replays with ScoreV1 and ScoreV2, playing with V1 and V2 doesn't change it either for me.

**Comment by Piotrekol** [comment]
osu! version, do you have compatibility mode enabled & are you playing/testing on bancho?

**Comment by Piotrekol** [comment]
unpack this somewhere on your disk and run it, is there constant spam of errors on the bottom right in that window while playing these replays? https://github.com/Piotrekol/ProcessMemoryDataFinder/suites/2468249747/artifacts/53058592

**Comment by PatyYe** [comment]
osu! version is on cuttingedge
And yes I do get a consistent spam: https://image.patyye.me/Code_ZGQseerCvM.png

**Comment by Piotrekol** [comment]
> do you have compatibility mode enabled & are you playing/testing on bancho?

**Comment by PatyYe** [comment]
I have compatibility off, tried enabling and restarting but no effect.
Playing/Testing on bancho ofcourse, wouldn't bother going on another server.

**Comment by Piotrekol** [comment]
what was last version that was working correctly for you, if any?

**Comment by PatyYe** [comment]
last working version for me was v210314.18 when I installed it for pool showcasing. After that I got an update the next week breaking it.

**Comment by Piotrekol** [comment]
[OsuMemoryDataProvider.zip](https://github.com/Piotrekol/StreamCompanion/files/6299186/OsuMemoryDataProvider.zip)
Drop this .dll into Plugins/Dlls folder and try again

**Comment by PatyYe** [comment]
hey, sorry for the late response.
Just tested it out and it works again!

**Comment by Piotrekol** [comment]
note that this dll breaks scoreV2 score reads(score will show as 0)

I might end up reverting this in SC and instead providing separate scoreV2(optional for memory reader) token

**Comment by PatyYe** [comment]
For my score isn't relevant as we run it for nice overlay and map stats. 
Score isn't shown as for showcase it's not relevant.

**Comment by Piotrekol** [comment]
fixed via 91f8354801da8a6cbb633085c567839dcf6a6ced.
will close once new release appears
