### ISSUE TITLE
Live PP Counting

### ISSUE THREAD

**Issue by Eternal-Suffering** [Piotrekol/StreamCompanion#288]
The PP counter isn't counting my "100s" "50s" and "Misses." I can only look at them after I finished the map and go to the replay system.

**Comment by Piotrekol** [comment]
same issue as #284?
try replacing memory dll provided in my comment here https://github.com/Piotrekol/StreamCompanion/issues/284#issuecomment-818060765

**Comment by Eternal-Suffering** [comment]
It worked thank you.
