### ISSUE TITLE
StreamCompanion Setup doesn't detect the map after uninstall and reinstall?

### ISSUE THREAD

**Issue by Foudre-1** [Piotrekol/StreamCompanion#291]
Hello.
I've recently decided to uninstall and reinstall StreamCompanion.
And after that, the setup doesn't detect any map (worked fine when I installed it the first time)
Here's a screen when I started the setup in administrator mode.
The id send me to last map I used the Companion with. https://osu.ppy.sh/beatmapsets/966190#osu/2022410

![image_2021-04-28_105139](https://user-images.githubusercontent.com/39246929/116375575-b59eef80-a80f-11eb-9cfa-2de420aa0fa3.png)

**Comment by Piotrekol** [comment]
Start SC with Ctrl and Shift pressed to show console with logs, are there any memory errors?
Reproduce your issue with that console running and send log file created in Files\Logs in SC install directory here.

**Comment by Foudre-1** [comment]
I tried twice with differents version of osu and it seems to be a memory error

[2021-04-28.txt](https://github.com/Piotrekol/StreamCompanion/files/6393656/2021-04-28.txt)

**Comment by Piotrekol** [comment]
this is a completely different/unexpected log result compared to what you have shown in the first screen.
Test again using build linked above https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/38918545/artifacts

**Comment by Foudre-1** [comment]
![image_2021-04-28_203115](https://user-images.githubusercontent.com/39246929/116454828-ae540200-a860-11eb-81ea-2fbf046f4947.png)
[2021-04-28.txt](https://github.com/Piotrekol/StreamCompanion/files/6394005/2021-04-28.txt)

Same thing again, maybe it is a problem with osu itself?

**Comment by Piotrekol** [comment]
Provide following information:
Are you playing/testing on bancho(official osu! server)?
What is your osu! version(stable/beta/cutting edge)? 
Do you have osu! compatibility mode enabled(check in osu! settings)?
Is osu! or SC running as administrator?

**Comment by Foudre-1** [comment]
Okay, that's weird and honestly I don't know what happened.
Apparently other apps that needed to access osu files like circle tracker and osu trainer were also returning errors.
I ran the Microsoft .NET Framework Repair Tool and now everything is working fine?
So yeah, osu is weird sometimes.
