### ISSUE TITLE
No reliable way to check for FC without missing slider tails

### ISSUE THREAD

**Issue by Henry-YSLin** [Piotrekol/StreamCompanion#294]
Currently, I am checking for an FC (one without any missed slider tails) using the following javascript in a web overlay
```js
let isPerfect = Vue.computed(
  () => getToken("combo") + getToken("comboLeft") === getToken("maxCombo")
);
```

However, this causes the `isPerfect` value to flicker when playing. It seems like the circle/slider that I am currently clicking is already subtracted from `comboLeft`, but isn't added to `combo` yet, causing `isPerfect` to be false when I am clicking the circle/slider and true when I am not clicking anything. Is there another way to get the `isPerfect` status reliably, excluding the object I'm currently clicking?

**Comment by Piotrekol** [comment]
With these 2 fixes above you'll still get flickers due to token value changes not being atomic, however these enable alternative solution:
```javascript
let lastTime = Number.MIN_SAFE_INTEGER;
let lastPerfectValue = {
  changedAt: Number.MIN_SAFE_INTEGER,
  value: true,
};
function setPerfectState(currentTime, isPerfect) {
  lastPerfectValue.changedAt = currentTime;
  lastPerfectValue.value = isPerfect;
}
let isPerfect = Vue.computed(() => {
  const tempIsPerfect = getToken('combo') + getToken('comboLeft') === getToken('maxCombo');
  const currentTime = getToken('time');
  //reset state on map restarts
  if (currentTime < lastTime) {
    setPerfectState(currentTime, true);
  }

  lastTime = currentTime;
  if (!tempIsPerfect && lastPerfectValue.value) {
    setPerfectState(currentTime, false);
  } else if (tempIsPerfect && !lastPerfectValue.value) {
    setPerfectState(currentTime, true);
  }
  return lastPerfectValue.value || currentTime <= lastPerfectValue.changedAt + 0.25;
});
```
