### ISSUE TITLE
Tokens Preview Resets When Restarting StreamCompanion

### ISSUE THREAD

**Issue by rufas1** [Piotrekol/StreamCompanion#295]
For example, unstableRate is originally outputted as a decimal {0:0.000} but I just want it to output as {0:0}. So I change it and it works nicely. There are no problems when using this ingame or in OBS Studio.

![image](https://user-images.githubusercontent.com/65890415/119588329-d0706f80-bd8d-11eb-9e10-878f3910a949.png)

However, when I restart StreamCompanion, it resets it back to {0:0.000}.

![image](https://user-images.githubusercontent.com/65890415/119583141-2d1a5d00-bd83-11eb-8d0b-f8872872120f.png)

I can change this every time I open up StreamCompanion, but there are other tokens I like to change too and it would be nice if the tokens were just saved to what I changed it to.

**Comment by Piotrekol** [comment]
Fixed via 95d43edf7f7453114a8da135cbec5da8a3e8c4b9 (settings sometimes were not saved due to this crash)
