### ISSUE TITLE
.net not working

### ISSUE THREAD

**Issue by NeeteXosu** [Piotrekol/StreamCompanion#296]
i have .net installed but streamcompanion tells me that i didnt have it installed

**Comment by omkelderman** [comment]
make sure you installed .net5 x86 Desktop Runtime

**Comment by ilsubyeega** [comment]
> make sure you installed .net5 x86 Desktop Runtime

duplicate of https://github.com/Piotrekol/StreamCompanion/issues/240#issuecomment-774656729
^, there is x64 and x86 exists at .NET 5, you would need the x86 for one.

**Comment by NeeteXosu** [comment]
> make sure you installed .net5 x86 Desktop Runtime

thank you man
