### ISSUE TITLE
It says virus ditected

### ISSUE THREAD

**Issue by jimmieboiiii** [Piotrekol/StreamCompanion#302]
When I try to download the osu! overlay it says "Failed - Virus detected". Can someone please help me!

**Comment by ilsubyeega** [comment]
Overlay injects osu game for rendering overlays, so it will be flagged to antiviruses. You might disable the antiviruses to use them, or you cannot use that tho.

**Comment by jimmieboiiii** [comment]
ok thx

**Comment by Piotrekol** [comment]
it's a false positive. add this file to your av exceptions if you wish to use overlay.
