### ISSUE TITLE
show mapset filepath 

### ISSUE THREAD

**Issue by OmegaBlurz** [Piotrekol/StreamCompanion#305]
https://i.imgur.com/Dg9vBhT.png Have where it says the osu directory location show the filepath of the song you are listening to.

**Comment by Piotrekol** [comment]
What would be the reasoning behind this? osu location is now shown in main window for users to know with osu! instance is used by SC when multiple osu!s are detected.

also, these can be pretty long.. not happening
![image](https://user-images.githubusercontent.com/4990365/125845904-d0e3f374-d46a-49fa-953b-3a08b475d890.png)
