### ISSUE TITLE
Not working for a certain map

### ISSUE THREAD

**Issue by Lyti4n** [Piotrekol/StreamCompanion#307]
https://osu.ppy.sh/beatmapsets/1114770 
I don't know why but it just doesn't work for this entire mapset.
Maybe its because of its really long name?

**Comment by Lyti4n** [comment]
Even stranger is that it works for the taiko diffs but not the std ones

**Comment by Piotrekol** [comment]
Cannot reproduce myself.
Start SC with Ctrl and Shift pressed to show console with logs.
Reproduce your issue with that console running and send log file created in Files\Logs in SC install directory.

**Comment by Lyti4n** [comment]
I just updated to the latest version which just solved the issue strange since it has been going on for like 3 months now but i never bothered to report it.
