### ISSUE TITLE
Mapset ID's

### ISSUE THREAD

**Issue by SimonDiamond** [Piotrekol/StreamCompanion#308]
With the latest update, I noticed that some mapsets do not have their mapset ID's. And no, I did not change them. Here is a video showcasing what I'm talking about: https://streamable.com/v6psbp

**Comment by Piotrekol** [comment]
This affects all pre-2010 maps(iirc), as these files do not contain BeatmapID/BeatmapSetID in .osu difficulty files.
Will be fixed in the next release - this data is available in memory.
