### ISSUE TITLE
"Enable average key counter" is greyed out.

### ISSUE THREAD

**Issue by Cabbleco** [Piotrekol/StreamCompanion#31]
Not implemented, or is this a problem on my end?

**Comment by Piotrekol** [comment]
I just never got around finishing it.
If I remember correctly you can simply enable it by going to settings and setting `EnableKPM` to True, however, it is both ugly and unconfigurable.

**Comment by Piotrekol** [comment]
Closing this, if you absolutely need something like this I'd recommend looking at other solutions, for example: https://github.com/yugecin/osukps
