### ISSUE TITLE
SC saying I need runtime when I have the correct one installed

### ISSUE THREAD

**Issue by DanteAmpora** [Piotrekol/StreamCompanion#311]
Really don't know what to say other then it's the "This program needs runtime. Would you like to install now?"
I've installed a bunch of different versions of the x86 runtime yet still nothing. I've tried removing those and installing the x64 ones
just in case. Same thing. I have the correct runtime installed again, x86, so please don't link me to issue #240. I've scoured that forum and a couple other and nothing is helping.

**Comment by ilsubyeega** [comment]
Seems it requires visual c++ redistributable?
May I get a screenshot of that alert?
Maybe if you want a direct support, try go to [Discord](https://discord.gg/N854wYZ)

**Comment by Piotrekol** [comment]
I believe this one was resolved on discord shortly after this issue was raised? reopen if that's not the case. I've tested manually on multiple occasions that installing x86 .NET5 inside windows sandbox(with does not have .net5 runtime by default) does work.
