### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by Phattyowo** [Piotrekol/StreamCompanion#313]
streamcompanion is detected as virus in windows defender which makes me unable to download unless i turn windows defender off.
![image](https://user-images.githubusercontent.com/88934594/129447568-3711f5da-f3d7-41b8-b312-caa9c97713a3.png)

**Comment by Piotrekol** [comment]
Caused by innoSetup itself.
Next release will contain portable/install-less zip archives next to setup files as an alternative.
This will be fixed in the future by replacing innoSetup.

**Comment by Phattyowo** [comment]
okay thank you very much!
