### ISSUE TITLE
Virus? 

### ISSUE THREAD

**Issue by Fwishys** [Piotrekol/StreamCompanion#314]
I know it probably isn't but windows and a few other virus software's are flagging JUST StreamCompanion-textOverlay.exe as a Trojan, You also cannot install it without disabling your antivirus, kinda annoying.

**Comment by Piotrekol** [comment]
https://github.com/Piotrekol/StreamCompanion/issues/313#issuecomment-898902466 & other duplicates

"portable" zip archives have same content as setup would have created(except for main setup) - use these if necessary until innoSetup is replaced
