### ISSUE TITLE
Virus?????

### ISSUE THREAD

**Issue by JibbyBop** [Piotrekol/StreamCompanion#317]
Hello, I have used StreamCompanion before and have loved it. I have not used it in a while due to switching between hard drives and fresh installing windows. I have used earlier versions before and have had no issue installing them. When I tried to install the most recent version chrome failed the download saying it had a virus. Any help would be great as I love using this software for streaming on twitch.

JibbyBop

**Comment by Piotrekol** [comment]
https://github.com/Piotrekol/StreamCompanion/issues/314#issuecomment-907853384
This is a false-positive machine-learning detection. Try installing/updating using portable zip archives instead of setup files, if adding an antivirus exception is not an option.
