### ISSUE TITLE
Accessing tokens via Javascript

### ISSUE THREAD

**Issue by CyberGen49** [Piotrekol/StreamCompanion#319]
As the title suggests, this is more of a question than an issue: How can I access token values in Javascript instead of using HTML placeholders? Apparently, I can't use the `getToken()` function on its own, resulting in a `getToken is not defined` error. 

For now, my solution is to create hidden HTML elements, each with their own token placeholders, and then access their `innerHTML` attributes to do my logic. It works, but there's gotta be a more elegant way to do this.

Responses appreciated!

**Comment by ilsubyeega** [comment]
You can get token values with websocket. Maybe the example exists in the source iirc

**Comment by Piotrekol** [comment]
`getToken` should be accessible inside of App.js setup function, in all overlays provided with SC.

If you mean basic usage.. without using any SC overlay/framework as template, then I'll let a snippet from soon-to-be-docs speak for itself:
![image](https://user-images.githubusercontent.com/4990365/133974464-89edda1c-8165-4938-a082-6b095ffcd89f.png)

**Comment by CyberGen49** [comment]
@Piotrekol That documentation looks very promising. I'll give it a shot tomorrow and report back.

**Comment by CyberGen49** [comment]
Yep, that works flawlessly! Consider this question answered.
