### ISSUE TITLE
Stuck on "nothing is playing at the moment"

### ISSUE THREAD

**Issue by Jalepers** [Piotrekol/StreamCompanion#325]
Yesterday it was reading my songs perfectly. Today i turned on my PC and it's been like this ever since. Ive tried reinstalling, reinstalling .NET, restarted my pc, tried fiddling with the settings, set my osu! folder manually, cutting edge and stable, and no dice.

**Comment by pavvvl** [comment]
I tried reinstalled SC and the setup is now telling me "Listening, id:0, is valid mapset:False". Even though I've done it before.

**Comment by Piotrekol** [comment]
osu! stable has updated with changes from beta/cutting edge. There should be new SC release available later today or tomorrow.

If you need it right now, see https://github.com/Piotrekol/StreamCompanion/issues/321#issuecomment-927310821
