### ISSUE TITLE
Stream Companion doesn't detect .NET

### ISSUE THREAD

**Issue by yuzoooo** [Piotrekol/StreamCompanion#327]
Whenever I launch SC I always get this error:

"To run this application, you must install .NET The framework 'Microsoft.WindowsDesktop.App', version '5.0.0' was not found. I installed .NET latest version, yet it still didn't work.

**Comment by Piotrekol** [comment]
As stated in latest release notes, SC doesn't require x86 version of .NET anymore.

Make sure that you have .net5 .NET Desktop Runtime installed... which should be the case if you're on updated version of windows 10
