### ISSUE TITLE
silver S rank display issue

### ISSUE THREAD

**Issue by Gerwazus** [Piotrekol/StreamCompanion#330]
PP counter is showing silver SS instead of single S even if you have 100's https://i.imgur.com/67QC8gA.png

**Comment by Piotrekol** [comment]
Can not reproduce, provide more info?
![image](https://user-images.githubusercontent.com/4990365/141467009-a201b7ef-6eb4-4d9b-85bc-683ed3a9212b.png)

**Comment by Gerwazus** [comment]
This is normal S. I'm talking about the silver S rank when you are using HD/FL mod
