### ISSUE TITLE
New PP hotfix

### ISSUE THREAD

**Issue by Lyti4n** [Piotrekol/StreamCompanion#333]
since there was a new hotfix when will these new values be implemented  (sorry if this the wrong place to ask)
edit: to clarify this is different to the rework that happened about a week ago which has already been implemented

**Comment by Piotrekol** [comment]
I believe the latest pre-release build should already contain up to date pp calc version ("hotfix" was added in 94cd8d8e27a8d6c7be96885d447bde711729d3e4, unless there was another one in the meantime)
new official release should appear either today or tomorrow after successful revalidation of pp values
