### ISSUE TITLE
Latest osu! stable update breaks StreamCompanion

### ISSUE THREAD

**Issue by CyberGen49** [Piotrekol/StreamCompanion#340]
The latest update to osu! stable ([changelog here](https://osu.ppy.sh/home/changelog/stable40/20220307)) seems to break StreamCompanion. None of the tokens work except for `osuIsRunning`.

I suspect something was changed under the hood that messed with things. I'm running the latest version of StreamCompanion.

**Comment by Piotrekol** [comment]
![image](https://user-images.githubusercontent.com/4990365/156993938-13064e87-cf86-4bd1-86c9-1043a8243a48.png)
![image](https://user-images.githubusercontent.com/4990365/156994015-c7d90b46-a55a-4631-9cc3-0f2060fdac69.png)
[StreamCompanionCEWorkaround.zip](https://github.com/Piotrekol/StreamCompanion/files/8195937/StreamCompanionCEWorkaround.zip)

Most likely I will not attempt to fix/search for this memory value until these changes trickle down to stable(if they do at all)

**Comment by TheMadN** [comment]
The ProcessMemoryDataFinder doesnt seem to be broken since other programs still work in the latest Stable build, like the alternatives to SC.  Thought mentioning that may be of help to you since youre the one behind PMDF as well.

**Comment by Piotrekol** [comment]
This is already fixed in pre-release build, and just awaiting some more testing to make sure it isn't broken before pushing a release.
