### ISSUE TITLE
i cant pass small test

### ISSUE THREAD

**Issue by escatone** [Piotrekol/StreamCompanion#341]
first im korean so im bad at english...

https://cdn.discordapp.com/attachments/894934655587999747/950700466394783804/2022-03-08_192237.png

I activated msn in osu, but pp counter does not recognize my beatmap files

how can I solve this problem?

i need your help

**Comment by Piotrekol** [comment]
Use workaround mentioned in my comment here: https://github.com/Piotrekol/StreamCompanion/issues/340#issuecomment-1060318591

Release with the proper fix should be available either today or tomorrow.
