### ISSUE TITLE
Why does it get flagged as suspicious 

### ISSUE THREAD

**Issue by CyGyGames** [Piotrekol/StreamCompanion#344]
I know this software is safe but can you explain me why the windows smartscreen appears that is trying to protect my pc when I'm trying to open it and it gets flagged on trapmine on virustotal and also if i am trying to send the download link to my friends on discord it also gets marked as suspicious

**Comment by Piotrekol** [comment]
#317 
low download/windows use count of latest release + unsigned executable + innoSetup being wack with AVs.
