### ISSUE TITLE
broken web overlay browser

### ISSUE THREAD

**Issue by lrscore** [Piotrekol/StreamCompanion#346]
Whenever I open the web overlay browser it takes me to this weird website where it's all just text. In OBS, where I used to have my overlays it only says shows "index of overlay/"
![Desktop Screenshot 2022 04 15 - 21 19 28 57](https://user-images.githubusercontent.com/103799686/163657850-d21004e5-f41c-4046-98e0-5bcf3e1c78aa.png)
![Desktop Screenshot 2022 04 15 - 21 21 12 75 (2)](https://user-images.githubusercontent.com/103799686/163657864-dc4f1fc2-ecff-4b62-bedf-f8facbba7e38.png)

**Comment by ilsubyeega** [comment]
I'm guessing that the content(files) of overlays/SC_URBar is not found, try reinstalling streamcompaion fully?
