### ISSUE TITLE
osu crashed immediately when in game overlay is installed

### ISSUE THREAD

**Issue by GNntGb** [Piotrekol/StreamCompanion#347]
I want to see the ur counter in my osu so i installed the in game overlay just now. However, osu crashed immediately for no reason when I open it. Reinstall sc isn't fix the problem. Am i doing something wrong during installation?

**Comment by Piotrekol** [comment]
Make sure you are not running any other overlays that are known to cause issues - known ones are listed in the wiki https://piotrekol.github.io/StreamCompanion/guide/in-game-overlays.html .

Post your list of loaded modules here(explained in Troubleshooting section in wiki) if it still refuses to work.

**Comment by MRZ0123** [comment]
since I got the same problem I'm going to continue the thread:

I went through the troubleshooting guide already, restarted my PC, reinstalled the entirety of StreamCompanion restarted my PC again and so on and so forth.
[2022-09-05.txt](https://github.com/Piotrekol/StreamCompanion/files/9491433/2022-09-05.txt)

**Comment by Piotrekol** [comment]
the troubleshooting section is for browser overlay, not text overlay that you currently use. Provide a log file from an attempt at running browser overlay instead.

**Comment by MRZ0123** [comment]
I removed the text overlay and added the browser overlay
[2022-09-05.txt](https://github.com/Piotrekol/StreamCompanion/files/9491716/2022-09-05.txt)

**Comment by Piotrekol** [comment]
Try turning your antivirus completely off(guard32.dll - Comodo) before starting osu! and SC. If that works, one of Comodo protections is preventing proper overlay injection

**Comment by MRZ0123** [comment]
Everything working fine now! Thx! The problem was that parts of the AV were still running after being deactivated (also still active after reboot). Solved by completely uninstalling the AV and running a garbage collection process.

**Comment by Piotrekol** [comment]
Closing as OP never responded in this thread before and your issue is solved.

As a side note, please do make sure that at least windows defender is active & running. Completly removing all AV software from your PC shouldn't ever be a proper solution
