### ISSUE TITLE
Since latest release/update (v220721.17) SC wont open.

### ISSUE THREAD

**Issue by FroxXyyy** [Piotrekol/StreamCompanion#352]
> Open before latest update.
> Click on update.
> Program closes.
> Cant be reopened.
> Restart PC.
> Reinstall StreamCompanion.
> no progress.

**Comment by FroxXyyy** [comment]
Found possible issue: .Net 6 did not install automatically as described in release notes.

**Comment by Piotrekol** [comment]
Weird, CI build from latest commit does indeed not install .net6, while one before it (8f036fd5cc58fa29db815d9b755d557a6fc4823d) does...

**Comment by Piotrekol** [comment]
Triggering CI build again on same commit seems to have somehow fixed it
