### ISSUE TITLE
why it create a new install in a different location on updates ?

### ISSUE THREAD

**Issue by BillyBaka** [Piotrekol/StreamCompanion#353]
title says it all . on update it does a new install in a different location than original install and its quite annoying. TY

**Comment by Piotrekol** [comment]
That would happen if after installing it in one location, it was moved manually to another. either move it back to original location, or reinstall and select new location during setup

**Comment by BillyBaka** [comment]
ok ... i think i used the installer but i may have just unzip and put it there .. ill see thanks.
