### ISSUE TITLE
Strain Graph is much flatter and less useful

### ISSUE THREAD

**Issue by Lyti4n** [Piotrekol/StreamCompanion#359]
The strain graph looks almost flat on most maps when it didn't before
while I don't have the graph from before
![osu!StreamCompanion_DlhNisFUcf](https://user-images.githubusercontent.com/85269866/197387098-9f92ccd1-92f4-4eb0-a85c-950fc8a4c22a.png)
this map is super diff spikey where the slightly higher sections are like 10 stars while the lower sections are like 4 stars
(map link https://osu.ppy.sh/beatmapsets/1538534#osu/3145600)

edit: this happens on all maps this is just an example incase I didn't make that clear

**Comment by Piotrekol** [comment]
Bug introduced while refactoring performance calculator. comparison before/after fix above:

<details>
<summary>1</summary>
https://osu.ppy.sh/beatmapsets/710587#osu/1502029  

![9Kk2gO48Me](https://user-images.githubusercontent.com/4990365/197417905-a262cd56-9362-46c3-9dce-5bd6334edbb1.png)
![P5zbPGHlrH](https://user-images.githubusercontent.com/4990365/197417909-9cf6efaa-981e-43e6-9688-3e33a7b3ba24.png)
</details>

<details>
<summary>2</summary>
https://osu.ppy.sh/beatmapsets/1824273#osu/3745412

![yA3bJxbniC](https://user-images.githubusercontent.com/4990365/197418004-fba60f88-c592-4e28-b5c6-802ccc21fcba.png)
![h6o2fzdGEm](https://user-images.githubusercontent.com/4990365/197418010-034431e3-6052-4a1a-8c1a-e7aef88d36d5.png)

</details>

<details>
<summary>3</summary>
https://osu.ppy.sh/beatmapsets/662208#osu/1401834

![eSJKfoWgYg](https://user-images.githubusercontent.com/4990365/197418030-1c20e60d-6683-4b10-a303-52348e27a68a.png)
![za75rAq2bT](https://user-images.githubusercontent.com/4990365/197418032-8acf58ed-3419-4be9-9cb5-8f0e566e8ea9.png)

</details>
