### ISSUE TITLE
Sorry but the fixes still havent been released its quite hard to use the software right now

### ISSUE THREAD

**Issue by Lyti4n** [Piotrekol/StreamCompanion#362]
is there anything holding it back?

**Comment by ilsubyeega** [comment]
I don't know about current situation however you can still access latest commit's build files. But please notice that there is no guarantee to work perfectly.
![image](https://user-images.githubusercontent.com/37479424/199767674-5c99a3aa-9827-4f92-bb31-b8ec4873806d.png)
![image](https://user-images.githubusercontent.com/37479424/199767712-9ae46c83-4093-480f-a65b-c305a92b4488.png)
![image](https://user-images.githubusercontent.com/37479424/199767763-88957f64-ccca-4048-a9f2-af956ec9aa0c.png)
