### ISSUE TITLE
stream compaion flashing problem

### ISSUE THREAD

**Issue by ALLVIS-II** [Piotrekol/StreamCompanion#366]
when I open the companion tab and open osu the overlay keep flashing while Im playing in the game it look like it will be flash while Im click the key on my keyboard. However, I can't see my my score ot pp stats properly. I try to ask my friend with it they say Ionly cannot have a mutiple overlay in the libary but it still happen after that I hope someone could help me with this issue.

**Comment by Piotrekol** [comment]
This is most likely an indication of you either running an unlimited frame rate in osu!, and/or your CPU struggling to generate overlay frames. Not much I can help there
