### ISSUE TITLE
Token Preview broken

### ISSUE THREAD

**Issue by awen478** [Piotrekol/StreamCompanion#378]
https://ibb.co/GtT6gtf when playing and watching replay it stuck at that value for anymap, https://ibb.co/99xsCHc when the map ending the value jump to end value no inbetween, ingame screenshot https://ibb.co/qJkpg11 it stuck at 25.9 the entire time but when the map ending it jump to 100 https://ibb.co/C8gZX2c

osu! version : [Stable 20230326](https://osu.ppy.sh/home/changelog/stable40/20230326)

**Comment by Piotrekol** [comment]
Duplicate of #372
same root cause
