### ISSUE TITLE
SC not recognizing when I'm playing

### ISSUE THREAD

**Issue by STPREAPER** [Piotrekol/StreamCompanion#379]
Whenever I play a map SC doesen't recognize that I'm actually playing and just displays max. pp possible from the map until the result screen. I tried changing back to stable from cutting edge and also downloading older version. Both versions worked just fine until about 2 weeks ago when it just stopped recognizing me playing a map. I think this is problem on my side but after trying to reinstall osu and changing the folders theres still nothing happening so I wanna ask for help.

**Comment by STPREAPER** [comment]
Tried both latest (v230327.15) and pre-latest (v230110.18) and both done using Installer

**Comment by STPREAPER** [comment]
Tried that with v230327.15 and v230110.18 both installer and portable on Stable 20230326, Stable 20230206 and Cutting Edge 20230319 not working on any of them. Also noticed that other players and streamers for example xootynator or miles have the same problem:
[https://imgur.com/a/KuXZb3x](url)
[https://imgur.com/a/wvE4WKE](url)

**Comment by Piotrekol** [comment]
Set log verbosity in settings to `Trace`, reproduce your issue (start SC, start osu!, try playing a map) and send logs saved in Files/Logs/ in SC install location.

These screenshots do not prove anything - for what it is worth, We have no idea if they are using SC in the first place.

**Comment by STPREAPER** [comment]
Thanks its fixed now.
Also sorry my brain didn't realize they could have it off
