### ISSUE TITLE
`localhost:20727/json` returns 500

### ISSUE THREAD

**Issue by Sclafus** [Piotrekol/StreamCompanion#384]
Hello, thanks for this amazing project.
I am trying to get the json output by contacting `http://localhost:20727/json`, but I get this error message:
```500 - Internal Server Error
The server has encountered an error and was not able to process your request.
Please contact the server administrator, informing them of the time this error occurred and the action(s) you performed that resulted in this error.
The following information may help them in finding out what happened and restoring full functionality.
Exception type: System.InvalidOperationException
Message: Nullable object must have a value.
```
This is with a completely new installation of osu! (not logged in) and StreamCompanion
If you need further info please let me know

**Comment by Sclafus** [comment]
Also, I noticed that the endpoint actually works after I close osu!
Steps to reproduce:
- Open osu! (not logged in)
- Open StreamCompanion
- Connect to [http://localhost:20727/json](http://localhost:20727/json)
- 500
- Close osu!
- Reconnect to [http://localhost:20727/json](http://localhost:20727/json)
- Actual output

**Comment by Piotrekol** [comment]
Check exception that should be saved in `<SC>/Files/Logs/<current_date>.txt`. My guess is on BanchoUser token, which is already fixed in prerelease.

**Comment by Sclafus** [comment]
The logs were empty in my case, but after logging in I was able to run it correctly. I will close the issue since you said it has been already fixed in pre-release. 
Thanks for the fast support!
