### ISSUE TITLE
PP Counter Value Doesn't Update

### ISSUE THREAD

**Issue by zSagey** [Piotrekol/StreamCompanion#397]
Basically the in-game overlay and browser overlay take forever to update the PP counter. It also shows the wrong 100, 50 and miss values. I have seen it randomly update in the middle of the play, but usually the PP counter wont move until I miss, theres a break in the song, or I pause. Any help fixing this?

https://github.com/Piotrekol/StreamCompanion/assets/75190612/f7909a69-ef43-4428-a141-2cb1644a341f

**Comment by Piotrekol** [comment]
upload your SC log located in `<SC>/Files/Logs/<date>.txt`

**Comment by zSagey** [comment]
> Saw this myself today - all values are updated correctly(on time), however, SC is updating & sending its values too fast for overlays using CountUp.js (11 out of 23 gosu overlays, none of SC_ overlays are using it). Solution here is to add optional websocket throttling for these to match(~9updates/s in gosu vs 40+/s in SC).

how would I go about doing this? Pretty inexperienced with whatever you're talking about haha
