### ISSUE TITLE
BrowserOverlay.BrowserOverlay could not be initialized? 

### ISSUE THREAD

**Issue by SHSHYLO** [Piotrekol/StreamCompanion#399]
![image](https://github.com/Piotrekol/StreamCompanion/assets/137472926/80a36fe2-bcbb-4292-b4a5-6c199f1e48f0)

IDK how this could have happened but I'm trying a fresh install now.

**Comment by Piotrekol** [comment]
update browser overlay by running latest browser overlay setup from releases
