### ISSUE TITLE
Can't process song input from osu! since v160926.17

### ISSUE THREAD

**Issue by ThePooN** [Piotrekol/StreamCompanion#4]
It seems osu!StreamCompanion can't process song input from osu! since v160926.17. The setup works fine and prints the right song, though. Beatmaps seems to be all loaded ("Loaded 13509 beatmaps").

Note that I'm using Wine 1.8 on Linux, but I don't see any change that could break that between [v160924.16 and v160926.17](https://github.com/Piotrekol/StreamCompanion/compare/v160924.16...v160926.17). I tried to delete the .db file and settings.ini (which triggers the setup again), setup detected the right song, but it didn't work past setup (stuck on "Nothing is playing at the moment").

Maybe something else changed, outside of the code itself (how you build it/build parameters/flags)?

**Comment by ThePooN** [comment]
v160924.16:
Having it enabled make SC not update when entering Playing state. Sometimes I can see this in the logs:
```wine client error:30: read: Mauvaise adresse
wine client error:ff: read: Mauvaise adresse```
"Mauvaise adresse" means bad address.
Most probably Wine related error/not having permission to read from osu! memory.

v160926.17:
Having it enabled or disabled makes no difference, still showing "Nothing is playing at the moment". Nothing different in Wine logs.
When it is enabled, I can still see messages like this in Wine logs when entering Playing state: ```wine client error:121: read: Mauvaise adresse```

**Comment by Piotrekol** [comment]
Have you checked if this is also the case on newest release?(v161030.20)

So from what you are writing, memory scanner never worked at all on linux. with is expected.
Open "settings.ini" with should be in the same folder as StreamCompanion executable, and 
edit first 2 lines to:
```
console = True
LogLevel = 100
```
This should show additional console window on startup. While this is in place, play ~2 maps(just stay in playmode for ~15s for each map) and paste output/screenshot of that console window there. Do this for v160924.16 & v160926.17 with memory scanner disabled.

**Comment by ThePooN** [comment]
On the newest release, the setup catches the song but when the main window appears no song is catched at all (Playing state or not). Same as v160926.17.

![image](https://cloud.githubusercontent.com/assets/4985725/20018487/2c8d5660-a2c8-11e6-9fcf-531b897c970b.png)

Strange. Despite the logs are looking the same, the window doesn't show the current song and the files don't update. And the memory scanner is disabled.

Also, having memory scanner enabled on v160924.16 doesn't make more log output.

**Comment by omkelderman** [comment]
that freakin ramdisk tho :ok_hand:

**Comment by ThePooN** [comment]
I always work in ramdisk folders when I'm working on temporary things. Otherwise shit stack up, stay there forever and I won't ever delete it.

**Comment by Piotrekol** [comment]
Since I had xubuntu installed in VM anyway I quickly setup SC & osu! in it using first 1/2 of [this guide](https://gist.github.com/Francesco149/a2f796683a4e5195458f4bb171d88eb0)(I just wanted it to "run")  
![vm](https://cloud.githubusercontent.com/assets/4990365/20030387/1ff31f6a-a364-11e6-80fd-be2280cb047d.png)
As you can see, it is working there(Files are saved correctly too) and I had same results with v160924.16 & v160926.17.
I honestly have no idea what's causing this on your end.

**Comment by ThePooN** [comment]
O GOD.

Is the memory scanner working?

**Comment by Piotrekol** [comment]
Seems like it actually fully works under linux... (apart from some ui weirdness)
![mem scanner](https://cloud.githubusercontent.com/assets/4990365/20031217/28d5e3aa-a374-11e6-8cd2-90736f6d9eba.png)
![mem scanner2](https://cloud.githubusercontent.com/assets/4990365/20031267/f99e556c-a374-11e6-996a-35281b838205.png)

**Comment by ThePooN** [comment]
aaaaAAAAAAAAAAAAAAAAAAAAAAAAA

Could you give the outvput of `wine --gversion`?

**Comment by ThePooN** [comment]
Oh wait if you're using Francesco's guide you should be on Wine 1.8.3, let me try that.

**Comment by ThePooN** [comment]
Oh God osu! doesn't even start using POL's Wine 1.8.3...
```
Unhandled Exception: System.ArgumentException: Font 'Arial' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet)
   at #=qDlyYd020$gb7cflqqFCRK8mH0WcSbZUEQxVTVyqeLY4=.#=qFo39h57UED0dPafW3OhV8MjwKkzpwo64ooj3b0NrmiE=()
   at #=qDlyYd020$gb7cflqqFCRK8mH0WcSbZUEQxVTVyqeLY4=..ctor(#=qXFW234S23PtamELoEARv5TnfRO4YRisUJCZavbS8a8ZsHctKJCW1gV_1vyBw4ae0 #=q5J0rOZCeCx9zX13CappS0CK7RX5adQ1A9zP1rMqmx80=)
   at #=qWuQUpFelVRw1x8X99m_O5A==.#=q0pKuyjnnWsOCStlqB3FTKA==()
   at #=qYgFvY1pQq_qWKGZ$F9XF1bcS504tECV$GTUMca08Atw=.#=qv4Vp12MSd9Qw1Rzngtts4w==()
```

That's gonna end in a full system reinstall I swear. :astonished: :gun:

**Comment by Piotrekol** [comment]
Yeah I did everything EXACTLY as it is described in that guide. That is everything in the "Installing osu! and tweaking sound latency" section
