### ISSUE TITLE
Patterns update slowly if TCP output is enabled, but no TCP client is connected

### ISSUE THREAD

**Issue by ceilingwaffle** [Piotrekol/StreamCompanion#40]
StreamCompanion version v181221.22

e.g. In this video: https://www.youtube.com/watch?v=PVl7Jzuv_To
The pp token updates once per second instead of several times per second. This only seems to occur if I have "Enable TCP output of patterns" checked, and only if no TCP clients are connected to the socket. As soon as I launch a program connecting to the socket, the pp updates at the correct faster rate.

**Comment by Piotrekol** [comment]
5c724c6
Nevermind, solution in last commit created a whole lot of new problems. 
I'll most likely end up using simple producer-consumer pattern here.
