### ISSUE TITLE
osu! crashing because unknown modules loaded during start up

### ISSUE THREAD

**Issue by Cosmiwu** [Piotrekol/StreamCompanion#406]
So, I just installed SC along with browser overlay plugin. After setting up, whenever I try to open osu! along with SC, it just crashes the game and shows this error (below screenshot). How do I fix this?
![Screenshot 2024-07-13 220921](https://github.com/user-attachments/assets/9f26c1d7-712c-48fc-84fa-364b294fa161)

**Comment by Piotrekol** [comment]
Join Discord server linked in readme for technical help, but general troubleshooting response I give for issues like this is:
* https://piotrekol.github.io/StreamCompanion/guide/in-game-overlays.html#troubleshooting
 * make sure you don't have any other overlays running (even if those do not display anything)
 * [Install vcredist](https://aka.ms/vs/17/release/vc_redist.x86.exe) if you just unpacked overlay/copied SC from another windows installation (versus installing using overlay setup)
 * Try **temporarily** disabling your antivirus & installing overlay again
