### ISSUE TITLE
Performance points not displaying correctly in osu!mania mode

### ISSUE THREAD

**Issue by c4p741nth** [Piotrekol/StreamCompanion#409]
In the osu!mania game mode, performance points (PP) are not being displayed correctly. While in other game modes, PP are shown normally, in osu!mania the value is consistently displayed as 0 (e.g. `mania_m1_000_000PP`).

This issue appears to be affecting the overall display of performance points in the osu!mania mode.

osu! mode (normal state)
![image](https://github.com/user-attachments/assets/0930f22c-7bbb-4533-94ba-8f606939eeea)

osu!taiko (normal state)
![image](https://github.com/user-attachments/assets/33dd676f-8ee0-49ed-a441-c5f9ee709047)

osu!ctb (normal state)
![image](https://github.com/user-attachments/assets/49540b54-f519-4fcc-a751-955ebc46ef9b)

osu!mania (zero value)
![image](https://github.com/user-attachments/assets/6a06d91e-d7c6-4e36-afd8-7833cb800c35)

Images from [palmEuEi](https://osu.ppy.sh/users/13656264)

StreamCompanion Version: 241106.19
osu! version: b20241030

**Comment by Piotrekol** [comment]
I did fix the root cause of this, however on quick glance mania pp in SC doesn't seem to match values on recent scores, eg. https://osu.ppy.sh/scores/mania/595247837. Needs more investigation.
