### ISSUE TITLE
!mXpp! tokens show incorrect values

### ISSUE THREAD

**Issue by ceilingwaffle** [Piotrekol/StreamCompanion#41]
StreamCompanion version v181221.22

e.g. In this video: https://www.youtube.com/watch?v=zIUVguoSMV4&t=45s

In that video, the "SS" value (!PpIfRestFced!) shows 1241.49 pp, but it should be 427 pp (map - https://osu.ppy.sh/b/1393701&m=0).

This seems to have been happening only since the latest update (v181221.22).

**Comment by Piotrekol** [comment]
can't reproduce

**Comment by ceilingwaffle** [comment]
The issue is actually with !mSSpp! not !PpIfRestFced!

The cause seems to be whenever you enable DT, the !mSSpp! always shows the pp for a DT SS, even if you disable DT, or switch to another map - every map you play from now on will show the DT SS pp, until StreamCompanion is closed and re-opened.

Here's a video demonstrating: https://www.youtube.com/watch?v=NuVBR4wTjY0

Output patterns: https://i.imgur.com/GfSp8PE.png

(I tested with and without TCP output enabled - both produced the same result).

**Comment by Piotrekol** [comment]
At some point I've made !mXpp! tokens not change their mod they calculate against if current mod in nomod ( b94639aecf34b6473dcfee51002d5f23d6006e11 ).
I was personally using that as a token in song select in combination with no-mod token (!xpp!).
Now that I think about it what I should have done instead is to just create more mod-specific tokens.

I'll revert that change in next release, sorry for the confusion.
