### ISSUE TITLE
Enhancement: Disable background in Live Visualiser

### ISSUE THREAD

**Issue by Devocub** [Piotrekol/StreamCompanion#47]
Additionally: ability to disable everything else, or at least change it's alpha to make it transparent.
Then it will be possible to make thing like this but for map strain.
![image](https://user-images.githubusercontent.com/2735824/54045395-95041d80-41e2-11e9-9d10-49f7566a9595.png)

**Comment by Piotrekol** [comment]
Background as in beatmap background or whole window background?

**Comment by Devocub** [comment]
In Live Visualizer

**Comment by Piotrekol** [comment]
In the newest release there's option to control color that's above beatmap background image but behind chart(image dimming color). 
You can set this color to black and set its alpha value to 255 to effectively remove background.

If I misunderstood, please clarify what you mean by removing background.
