### ISSUE TITLE
app crashes when osu is on

### ISSUE THREAD

**Issue by browiec** [Piotrekol/StreamCompanion#48]
everything works fine until I launch osu. then the app crashes immediately with this message:
![image](https://user-images.githubusercontent.com/48485400/54210132-3808b000-44df-11e9-8e34-3e581bd87262.png)

tried removing various plugins and reinstalling, neither worked.

**Comment by Piotrekol** [comment]
Install .net framework 4.7.2. Next version will explicitly require it.

2019-03-12 16:04 GMT+01:00, browiec <notifications@github.com>:

**Comment by Piotrekol** [comment]
Actually no, I confused that with another issue. Either download nightly
build (appveyor) as it's already fixed, or wait for next release.

wt., 12 mar 2019 o 16:04 browiec <notifications@github.com> napisał(a):

**Comment by Piotrekol** [comment]
https://github.com/Piotrekol/StreamCompanion/releases/tag/v190313.16
