### ISSUE TITLE
mod detection in watching mode

### ISSUE THREAD

**Issue by Nodebuck** [Piotrekol/StreamCompanion#5]
So, currently when spectating or watching a replay the `!mods!` variable is empty. Is this expected behavior or is mod detection while watching just not implemented?

Is there any way this could work by changing the offset for the memory scanner? 

Running the wizard for detecting the offset doesn't work unfortunately when spectating someone playing the map.

**Comment by Piotrekol** [comment]
That's intended.
memory searcher [is configured to only work when you're playing](http://i.imgur.com/alzBVMm.jpg).
To be honest I had to double check why is that. 
Memory region I'm scanning contains only your currently choosen mods in song select. Even when I enabled scanner for watching status, It corresponded to mods I had active in song select.

I might later look for other memory region that both contains this data and is easily traceable(I do not want to release SC update for every osu! release)

In the end, this wouldn't be needed if osu! provided this by itself, but I guess "coming in lazer" is earliest we'll get this.
