### ISSUE TITLE
Can't seem to load anything.

### ISSUE THREAD

**Issue by RazorApple** [Piotrekol/StreamCompanion#51]
Shows 
Loading 0 of 447 always.

Reinstalling did nothing.

**Comment by Piotrekol** [comment]
Would you mind sending me your osu!.db privately? Either discord or osu! PM message works.
Overall logging around map/osudb loads needs improving.

**Comment by RazorApple** [comment]
What is your discord?

**Comment by Piotrekol** [comment]
You can find discord link listed in the readme, but here: https://discord.gg/N854wYZ
And playing offline shouldn't matter, at least for loading of beatmaps.

**Comment by RazorApple** [comment]
Look in your dms

**Comment by Piotrekol** [comment]
Custom osu!.db, won't go into details. wontfix
