### ISSUE TITLE
OBS cursor duplicator bug

### ISSUE THREAD

**Issue by Fleepy** [Piotrekol/StreamCompanion#55]
When you capture the StreamCompanion window, wherever you put your cursor, it duplicate's it.

https://clips.twitch.tv/CharmingSmoggyWitchGOWSkull

**Comment by Piotrekol** [comment]
Recheck with newest release please. There was bigger issue where obs wasn't really able to capture that window.

**Comment by LosTigeros** [comment]
Yeah 100% sure that was caused by `AllowTransparency` option.
I had (and still have) the same problem in my app but I can't remove it because of design I have 🤔 

Btw it works fine with `AllowTransparency` on when you capture entire desktop 😄

**Comment by Piotrekol** [comment]
There's no point to `AllowTransparency` for visualizer then, if obs can't capture it correctly with transparency. 

When you capture entire desktop and just cut up rect containing that window, you're basically giving up ability to display anything under that window on obs scene. Same thing can be achieved with allowing to change default background color.
Also there's another issue where with only 1 screen you can't really capture entire desktop while playing to show that window, can you ;)?
