### ISSUE TITLE
Ingame overlay doesn't load in

### ISSUE THREAD

**Issue by Aloovn** [Piotrekol/StreamCompanion#59]
Nothing happens when I press on "show in osu"

Thanks in advance,

-Aloo

**Comment by Piotrekol** [comment]
https://github.com/Piotrekol/StreamCompanion/wiki/8.-Ingame-overlay-display

**Comment by Aloovn** [comment]
Done all of that already, doesn't help.

Thanks for answering tho...

-Aloo

**Comment by Eroo36** [comment]
https://github.com/Piotrekol/StreamCompanion/releases 
You gotta download overlayPlugin.zip and add it to the files yourself
