### ISSUE TITLE
StreamCompanion Displays Incorrect DiffName

### ISSUE THREAD

**Issue by staticsn0w** [Piotrekol/StreamCompanion#6]
For example, i'll be playing Gabba Front Berlin - Lacrima Mosa Est [MEGA's Insane] and StreamCompanion will say that im playing Gabba Front Berlin - Lacrima Mosa Est [Hard]

**Comment by Piotrekol** [comment]
I'm unable to reproduce this.
Was this map hot-loaded?(have you added new beatmap while SC was running, and haven't restarted both since?)
Was memory scanner enabled?
Are you able to somehow reproduce this?

**Comment by staticsn0w** [comment]
I've tried restarting osu! and SC to no avail, memory scanning is enabled, and I don't have anything else i can use to test if this is reproducible. Should I try reinstalling?

**Comment by Piotrekol** [comment]
I think reinstalling SC/osu! won't change anything.
If it's not reproducible then there's nothing I can do.
Memory scanner is there to ensure there are no mismatches of beatmap sets/diffs while playing, and if for some reason it cannot do its job, all should revert to string matching against your current maps in cache.

**Comment by YKilin** [comment]
I have the same problem. Memory scanning is enabled, but it seems that SC just display a default DiffName.
And the DiffName won't update if I select another difficulty.
![](https://user-images.githubusercontent.com/24877906/35777334-1e4a79de-09e7-11e8-837e-dcc9bd605dc3.png)
![](https://user-images.githubusercontent.com/24877906/35777337-2888ef84-09e7-11e8-80e8-057b25d4de7b.png)
