### ISSUE TITLE
way to take off picture from live visualizer

### ISSUE THREAD

**Issue by cat1322** [Piotrekol/StreamCompanion#60]
is there a way to take off the thumbnail of the song your playing so its just the pp counter box??

**Comment by Piotrekol** [comment]
You mean, you want to completely remove upper part of that window? https://i.imgur.com/zqg7vTI.png
Or: only remove thumbnail and keep strain chart? https://i.imgur.com/1ez9W87.png

**Comment by cat1322** [comment]
Completely remove the upper part

**Comment by cat1322** [comment]
> 
> 
> You mean, you want to completely remove upper part of that window? https://i.imgur.com/zqg7vTI.png
> Or: only remove thumbnail and keep strain chart? https://i.imgur.com/1ez9W87.png

remove the upper part of that window

**Comment by cat1322** [comment]
@Piotrekol so is there a way?

**Comment by Piotrekol** [comment]
Yes. I'll make it so top/bottom shared height can be changed. you'll be able to achieve [this](https://user-images.githubusercontent.com/4990365/56311536-8cdabe80-614e-11e9-94b1-00acd7b84fea.png) and [that](https://user-images.githubusercontent.com/4990365/56311575-ac71e700-614e-11e9-9998-dc264e393643.png)
Then I'll remove safety min height, so only that bar can be displayed without the need of stretching it.

I plan on allowing adding SC patterns+custom things to that window, but I have no ETA on that so this will have to do for now.

**Comment by Piotrekol** [comment]
36915d87e275da871714c1b00ce00845896274ee + 33eb65a0bf599563563f2e7c5251fc4de878d05b

![image](https://user-images.githubusercontent.com/4990365/56314682-01fdc200-6156-11e9-861d-de527ad70e8f.png)
![image](https://user-images.githubusercontent.com/4990365/56314705-0fb34780-6156-11e9-8bd7-86760df20390.png)
![image](https://user-images.githubusercontent.com/4990365/56314763-44bf9a00-6156-11e9-8ad5-a8ea5813d328.png)
