### ISSUE TITLE
Add the ability to resize info section in visualizer

### ISSUE THREAD

**Issue by InvisibleSymbol** [Piotrekol/StreamCompanion#61]
Currently if you make the LiveVisualizer fullscreen (so 1920x1080) it looks something like this
![](https://kayo.moe/lomVbw6J.jpg)
I would like to have the ability to change the size of the info section at the bottom.

The planned use is putting it behind the osu gameplay, something like this:
![](https://kayo.moe/PpMdwtI0.jpg)
As you can see, with the section this big, it looks pretty bad.

**Comment by Piotrekol** [comment]
Adding along with #60 :)

**Comment by InvisibleSymbol** [comment]
Yay, tyvm

**Comment by InvisibleSymbol** [comment]
Also this may be the wrong place for it but please, _please_, add the option to disable rounded corners. If you want I can create an issue, just seemed like to minor for a new issue.

**Comment by Piotrekol** [comment]
Sure, will appear as a toggle.
