### ISSUE TITLE
Install exe isn't signed

### ISSUE THREAD

**Issue by eenpersoon64** [Piotrekol/StreamCompanion#62]
When I downloaded the latest release from the release page and tried to run it, I got greeted with this screen.
![image](https://user-images.githubusercontent.com/37511342/55538106-f58d5a00-56bd-11e9-8e9a-5c08f45addd2.png)
Basically, it says it has prevented an app from an unknown publisher from starting. So, maybe sign your code to prevent things like this from happening and people from freaking out

**Comment by Piotrekol** [comment]
Then purchase code signing license for SC. I'll gladly accept it.

czw., 4.04.2019, 09:44: eenpersoon64 <notifications@github.com> napisał(a):
