### ISSUE TITLE
PP Rounding

### ISSUE THREAD

**Issue by P2LOVE** [Piotrekol/StreamCompanion#63]
Add a command like !PpIfMapEndsNow!, but with rounded PP.
727.27 pp will pe rounded up to 727 e.g

**Comment by Piotrekol** [comment]
Already possible using newest nightly build.

>

**Comment by P2LOVE** [comment]
No new updates found (v190324.10)  (c)

**Comment by Piotrekol** [comment]
I use "nightly build" as a build that's unreleased and might change considerably before release.
Here are images I've made for other user some time ago as to how to get newest one:
https://i.imgur.com/keiayto.png
https://i.imgur.com/CBBIwad.png

**Comment by P2LOVE** [comment]
oh, ok :)
