### ISSUE TITLE
Install Directory

### ISSUE THREAD

**Issue by 207h** [Piotrekol/StreamCompanion#64]
Please, let us choose the install directory, the original install directory is now broken (maybe corrupted by StreamCompanion itself) so please let me choose another spot other than my Boot-SSD

**Comment by Piotrekol** [comment]
Installer won't ask for install path if you have SC already installed. If
you want to change install path you need to uninstall then it'll ask you
for new location.

**Comment by 207h** [comment]
It was just fucked up, it was installed but not working deinstalled it in the "Apps & Features" in the Settings and now it installs fine, sorry for the issue.

**Comment by Piotrekol** [comment]
"fucked up" doesn't really help in tracking down if something was actually broken because of SC itself.
But I'm glad that you managed to fix it :)
