### ISSUE TITLE
Can't pass small test

### ISSUE THREAD

**Issue by miRemid** [Piotrekol/StreamCompanion#66]
Always waiting..![](https://i.loli.net/2019/06/02/5cf3cd268bc4845495.jpg)

**Comment by Piotrekol** [comment]
Make sure that Stream Companion is not getting sandboxed by your antivirus(windows defender included).

**Comment by miRemid** [comment]
thank you but useless.. and when i run it as admin, it can't recognize the osu! process

**Comment by Psypherical** [comment]
I was able to replicate this bug by having MSN enabled in osu! before the setup requested to user to do so and by closing the setup on said prompt. The solution to this problem would be to disable MSN, uninstall StreamCompanion, and reinstall it. However, there is some odd behavior in which the prompt to enable MSN only disappears once you've closed and reopened osu! Do that, and follow the setup as normal.

**Comment by ExModify** [comment]
I have the same problem. I don't have antivirus at all, the method above didn't work either for me. I tried running it with admin privileges, but I had the same problem as miRemid. It gave this though when I opened it in Visual Studio and got to the test:

System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=Only part of a ReadProcessMemory or WriteProcessMemory request was completed
  Source=ProcessMemoryDataFinder
  StackTrace:
   at ProcessMemoryDataFinder.API.ProcessMemoryReader.ReadProcessMemory(IntPtr memoryAddress, UInt32 bytesToRead, Int32& bytesRead)

I have osu! running on full screen (doesn't work in windowed either) on Windows 10 Enterprise 1903

**Comment by Piotrekol** [comment]
Out of curiosity: can you try removing settings.ini file from SC folder and try passing StreamCompanion setup again(remove that file on each attempt).
Not sure if that's the issue you're all facing or not, but if you exit at any point in the setup without completing memory step it'll save these ..."2 nice settings" in settings.ini:
```
EnableMemoryScanner = False
EnableMemoryPooling = False
```
You can guess what will happen on future attempts(tip: that file is never reset)

I'll be fixing this anyway in a moment, but please tell me if this manual method works for you or not.

**Comment by ExModify** [comment]
With this new build, it works for me just fine.
![image](https://user-images.githubusercontent.com/13742864/63209642-d2e76500-c0e3-11e9-85e1-2f88db5cebfc.png)
