### ISSUE TITLE
error report and crash

### ISSUE THREAD

**Issue by Blazinganglez2** [Piotrekol/StreamCompanion#69]
So this error message shows up when osu is playing a song that isn't circles. When osu is off it stays on but if it's playing a song on osu. The error shows. not sure what else to say but confused. it's not the visualizer cause i tested to turn it off and it still shows. the text for the song shows then the error shows but when your switching songs it stays.
![problem](https://user-images.githubusercontent.com/40573582/59698392-d4acaf00-91ac-11e9-9b56-4bec386e579f.PNG)

**Comment by Piotrekol** [comment]
Please check if that's resolved in newest release.

**Comment by Blazinganglez2** [comment]
it's showing something else now 
![problem 2](https://user-images.githubusercontent.com/40573582/59731402-339d1300-9203-11e9-905b-471a11312f8c.PNG)

**Comment by Piotrekol** [comment]
None of the error reports for this issue indicate usage of newest SC version. Update before trying again.
Will assume fixed if nothing appears on automatic error reports for new release.

**Comment by Blazinganglez2** [comment]
I've downloaded the next update to see if it was a glitch twice and the error still shows up. I even reinstalled stream companion to see if it was a bug in code with the version i originally got it. And it still shows this error. I can't see anything that can fix it for my side and even when you made a updated version to fix this little problem. 
![problem 2](https://user-images.githubusercontent.com/40573582/59740307-edf14200-9224-11e9-95dd-d84ebfa2a236.PNG)
  
![verson](https://user-images.githubusercontent.com/40573582/59740195-97840380-9224-11e9-9c9f-35867d10f4a8.PNG)

**Comment by Piotrekol** [comment]
While I was able to reproduce this problem once at first(when I first responded), I'm not able to anymore.
I even tried updating [manually version-by-version all the way from v190415.17](https://user-images.githubusercontent.com/4990365/59784203-2f83fa80-92c2-11e9-8603-2e042f1ebb89.png) checking osu! integration each time, with no results. 
While I'd like to have this fixed since you're not alone with this issue, have you tried full SC reinstall?(if you want to backup your config.ini, uninstall SC, install it again)

**Comment by Blazinganglez2** [comment]
i uninstalled the software by my pc and reinstalled it. had the same problem so i went through the folder and there was a uninstall application. i didn't see that when going through. so when i tested the software and it works now. if i seen that uninstall thing after the problem was showing up this would have ended. thanks for adding the new update to fix it and for anyone having this issue. goto the folder with the thing and uninstall it with the program not by your pc.
