### ISSUE TITLE
.Net Framework Issue

### ISSUE THREAD

**Issue by yokees2** [Piotrekol/StreamCompanion#70]
So i have problems with windowns 10 blocking .Net Framework versions that i need to open this application, as right now its 4.7.1 or 4.7.2. Any help ?

**Comment by yokees2** [comment]
Is there version of Stream Companion that supports 4.8 ?

**Comment by Piotrekol** [comment]
No there is not. I've updated all SC components to use 4.7.1 .net 3 days ago. 
You never provided any information what is actual issue. And if anything, Windows 10 will install missing net framework on launch if necessary.
