### ISSUE TITLE
playing & listening overlap on result screen

### ISSUE THREAD

**Issue by InvisibleSymbol** [Piotrekol/StreamCompanion#71]
The setup is as follows:
- Pattern1 with `!sspp!` and Save event `Listening`
- Pattern2 with `!ppifmapendsnow!` and Save event `Playing` (forced)
- The Patterns are read using the OBS Plugin.

When selecting & playing a map, the behavior is as expected, the corresponding Patterns are shown.
![select screen](https://kayo.moe/p12N7V6z.png)
![playing screen](https://kayo.moe/vgDTaN6d.png)

The issues is after completing a map and coming to the result screen, both patterns are triggered and they overlap.
![result screen](https://kayo.moe/xKe9HHtq.png)

The solution to this would be to not trigger listening on the result screen, since it doesn't make sense to begin with (on the result screen you aren't "listening" to the song since it already ended)

**Comment by Piotrekol** [comment]
Should be fixed in next release.
52c793987eed386cf62e4a8c8c6f8a4c9ffa1037 2140d792a0524d3b391cabe2120d5f1a4df67870 78c3df59d67966e9eae16dc47709cf553f26d1b8

**Comment by InvisibleSymbol** [comment]
As far as I can see listening is still being triggered...
![](https://i.fiery.me/HClj.png)
![](https://i.fiery.me/kXV6.png)
![](https://i.fiery.me/Bd9a.png)
This is the latest commit compiled myself (Couldn't wait, sry c:)

**Comment by Piotrekol** [comment]
Make sure to select correct pattern save events (works just fine there) https://puu.sh/DXX6r.mp4
![image](https://user-images.githubusercontent.com/4990365/61992383-c2e8e200-b05d-11e9-9bf8-cc139f00da66.png)

**Comment by InvisibleSymbol** [comment]
Shows correct version, so I assume my build worked correctly... (Also star rating is broken, no idea why)
![](https://i.fiery.me/wj5o.png)
These are my settings, basically the same as yours.
![](https://i.fiery.me/GfzZ.png)
listening still triggers ¯\\\_(ツ)\_/¯

**Comment by Piotrekol** [comment]
Re-check on newest SC version please.

**Comment by InvisibleSymbol** [comment]
fixed on the latest release, guess my build didn't work...

**Comment by Piotrekol** [comment]
just a guess, but maybe you didn't do full rebuild of the project after pulling changes
