### ISSUE TITLE
updater doesn't support different program location

### ISSUE THREAD

**Issue by InvisibleSymbol** [Piotrekol/StreamCompanion#72]
When the program is moved to a different disk, the updater will attempt to install the update in the original location, resulting in a new installation and the other one not being updated. 
Solution: Updater should use the dir the program is located at.

**Comment by Piotrekol** [comment]
all updater does is:
1. determine wherever update is necessary by calling github api
2. download setup exe.
3. run setup exe with silent flags.

Multiple SC installations are obviously not supported, and your possible use case (multiple SC configurations will be solved by coming feature that will allow you to switch between configuration "profiles" in settings)

**Comment by InvisibleSymbol** [comment]
well, my use case is not multiple sc installations configurations, I just want a different install location. Not sure if switching between configuration profiles would help in that case. (Multiple installs is just a side-effect occurring when updating)

**Comment by Piotrekol** [comment]
re-tested again.. you can select any SC install location(fresh install) and all SC updates are properly installed in the same location.
