### ISSUE TITLE
!msspp! doesn't update after selecting a new mod

### ISSUE THREAD

**Issue by InvisibleSymbol** [Piotrekol/StreamCompanion#73]
`!msspp!` only updates after a map has been started, making it impossible to know the pp of the mods selected without starting the map.
Solution: Update `!msspp!` everytime a new mod is selected.

**Comment by InvisibleSymbol** [comment]
same with all other commands having a `m` prefix, for example !mbpm!

**Comment by Piotrekol** [comment]
Requires changes in [ProcessMemoryDataFinder ](https://github.com/Piotrekol/ProcessMemoryDataFinder) as currently it is only able to get mods data when playing/listening.
