### ISSUE TITLE
after unpack the overlay plugin i start the .exe and it gives me this error

### ISSUE THREAD

**Issue by InjectedBoi** [Piotrekol/StreamCompanion#74]
![Capture2](https://user-images.githubusercontent.com/52336906/60377605-b9496b80-9a18-11e9-8f4a-57680907b251.PNG)

**Comment by Piotrekol** [comment]
You need to unblock osuOverlayPlugin.dll (inside Plugins folder) https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/
