### ISSUE TITLE
Change position for ingame outputs doesn't work properly

### ISSUE THREAD

**Issue by Eroo36** [Piotrekol/StreamCompanion#78]
first screen : [1](https://puu.sh/DZUtx/48412b5e46.png)
second screen(i drag and use this position and save it) : [2](https://puu.sh/DZUub/f891e13f96.png)
third screen : [3](https://puu.sh/DZUuR/368705a1e0.png)
Looks like it is getting Y value and putting into X value and it doesn't even get my X value,
But if i put all values by hand it works fine so it is not a major issue.

**Comment by Piotrekol** [comment]
Yeah.. this window has been a little broken from the start, but as you said X and Y cords can be entered manually. Will see if that can be fixed soon.
