### ISSUE TITLE
StreamCompanion won't open after update

### ISSUE THREAD

**Issue by unlucky4ever** [Piotrekol/StreamCompanion#8]
I downloaded the latest update that you just released, and now my StreamCompanion won't open at all.

No error messages of any kind, it just gives me a loading cursor for a few seconds, and then nothing. I've uninstalled it completely (even deleted all the files it made) and reinstalled it, still the same thing happens. Tried running it as an administrator as well, also nothing.

Using Windows 10 Pro 64-bit.

**Comment by Piotrekol** [comment]
Temporally fixed by reverting MSN fix 421e7c3b09e276a5fb9f957878d595baf561d2cc
