### ISSUE TITLE
[Feature request] Live token for unstable rate.

### ISSUE THREAD

**Issue by ab996abeed** [Piotrekol/StreamCompanion#81]
What the title says. Possible? I assume it's calculated on the fly as you're playing, so should be stored in memory.

**Comment by Piotrekol** [comment]
` I assume it's calculated on the fly` 
It's sadly not. It is calculated only at the results screen.

**Comment by ab996abeed** [comment]
Ok, that's a bummer, I was hoping it'd be simple to implement.

For a use case, I guess having it would be useful as players (and viewers) could see how consistent their hits are on different parts of a map. Could even draw a UR graph in the visualizer as the map is played.

**Comment by Piotrekol** [comment]
Will be added in next release as !UnstableRate! live token
