### ISSUE TITLE
Feature reequest: change StreamCompanion files save location

### ISSUE THREAD

**Issue by Thymue** [Piotrekol/StreamCompanion#88]
I want to change where streamcompanion saves its files either ability to change where all the files are saved or ability to change it for every file in Output Patterns would be nice or you can do both

**Comment by Piotrekol** [comment]
[this is the line](https://github.com/Piotrekol/StreamCompanion/blob/master/osu!StreamCompanion/Code/Core/Savers/FileSaver.cs#L10) responsible for defining location of saved files across all SC plugins. 

In the past(iirc before SC went opensource) you were able to edit smillar variable with lead to a lot of issues with:
1. folder access permissions
2. setting location to portable disk (and said disk disappearing at some point)
3. users defining network folders as save locations and complaining things were slow.

Not sure if I want to re-add that functionality again. Do you have any specific reason why you would need this?

**Comment by Thymue** [comment]
Thanks for replying, I found out I can just use memory map instead so I don't have any reason for it anymore.
