### ISSUE TITLE
[Feature Request] allow live tokens to be saved even when not playing

### ISSUE THREAD

**Issue by surepy** [Piotrekol/StreamCompanion#89]
for example, If I want the "time" live token to be constantly printed out to obs, it's not possible to do that as the "save event" option is grayed out and it only appears when I'm playing.

**Comment by Piotrekol** [comment]
that is actually by design, other than time token, all underlying values are available for reading only when playing. Will consider exposing time token alone

**Comment by surepy** [comment]
yea i understand that but thought it was unnecessary on the time token

that seems like a fine solution thanks
