### ISSUE TITLE
Won't calibrate no matter how many times I uninstall and reinstall

### ISSUE THREAD

**Issue by 1800yungbert** [Piotrekol/StreamCompanion#93]
I installed this companion on my old pc with no issue, that was back in may or june. But now when I tried installing it, I did all the regular requirements to get it prepped for calibration. But whenever i use the mods it asks for and the same song it gives me, it can never calibrate, it just gives me "waiting..." I'm not too sure what is wrong here. I just want to get this set up for my stream.

I also uninstalled and reinstalled about 5-6 times already, Deleted all existing files of the program before reinstalling as well. Same result every time.... "Waiting...."

**Comment by 1800yungbert** [comment]
cmon man, it's like you've gone completely MIA on this project. I'd really like to have this back on my new setup but i guess you don't care about the project anymore lol

**Comment by Piotrekol** [comment]
fyi. I'm still waiting for you to answer to my message on discord since you were one that also asked for help there lol...

**Comment by 1800yungbert** [comment]
welp. my apologies lol, I kept going on and on uninstalling and reinstalling i ended up getting really frustrated, thanks for the build dude my bad for jumping to conclusions lol
