### ISSUE TITLE
SC crashes when Live Visualizer is enabled, works fine otherwise

### ISSUE THREAD

**Issue by beta1hit** [Piotrekol/StreamCompanion#96]
Whenever Live Visualizer is enabled, SC quickly crashes; it can never run for more then about 10 seconds, sometimes it can "survive" but only till I switch the mapset in osu!. Mostly SC just vanishes, very rarely I've gotten a popup along the lines of "an unexpected error came up and SC had to close. This has been sent to Piotrekol" or so. 

SC works 100% fine with Live Visualizer disabled, just enabling it in the settings will make SC start crashing.

If I'm lucky I can get into the settings and disable Live Visualizer without SC crashing beforehand. But I'd like to use the Live Visualizer :(

Tried reinstalling, no change.

i7 6700k, 16gb ram, rx vega 64, dual monitors

C:\Program Files (x86)\StreamCompanion\Files\Logs is empty, I've seen people post other logs when opening new issues, which additional stuff / files would be required info about my setup?

**Comment by Piotrekol** [comment]
`very rarely I've gotten a popup along the lines of "an unexpected error came up and SC had to close. This has been sent to Piotrekol" or so.`
Can you send me your windows username(or PC name if your username is generic one) there or on discord, so I can look at these specific reports?

Also, please check if the same problem occurs on newest nightly build: https://i.imgur.com/keiayto.png https://i.imgur.com/CBBIwad.png

**Comment by Piotrekol** [comment]
https://sentry.io/share/issue/7c3fd3ca698a4bffa37b414a0f712028/
&
https://sentry.io/share/issue/307033ef282742ccb64868cc75dd0b05/

Will look into later today, but I'm fairly sure you have some funny windows setting set somewhere.

**Comment by Piotrekol** [comment]
\+  https://sentry.io/share/issue/2da84cb477f74611b4e18600d875a3af/
\+ [several others](https://user-images.githubusercontent.com/4990365/65986167-a2853b80-e483-11e9-8a68-cb26a2a2eef2.png) that I'm not going to link since they all point to same piece of internal ms code.

I can't figure out why and where exactly it is breaking. I can't reproduce this and this is first time that this problem has arisen.

Maybe try fixing your .net framework installation?

**Comment by beta1hit** [comment]
After more troubleshooting, I even tried doing a brand new install of Windows, just installing osu! and SC on that, still same issues. I think this issue seems to relate to something about my hardware. Closing this issue for now

**Comment by beta1hit** [comment]
misclick

**Comment by Piotrekol** [comment]
Not sure what to do with this one, have you re-checked on recent SC versions? Visualizer now has hardware-acceleration forced off, with might have solved your issue.
Please re-open if this is still happening.
